eclipse-ee4j/mojarra

impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java, impl/src/main/java/com/sun/faces/application/view/ViewHandlingStrategyManager.java, impl/src/main/java/com/sun/faces/config/ConfigManager.java, impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/config/processor/ApplicationConfigProcessor.java, impl/src/main/java/javax/faces/application/ViewHandler.java, impl/src/main/resources/com/sun/faces/standard-html-renderkit.xml, spec/DEPRECATED.md
=> Fixes issue #4395 - Remove DisableFaceletJSFViewHandlerDeprecated

.travis.yml
=> Fixes issue #4408 - Add TravisCI file

.travis.yml, test/pom.xml
Added automated testing for the test/htmlunitaware directory against Glassfish 5.0. 
=> Fixes issue #4410 - Add Glassfish automated testing to TravisCI file

.travis.yml
Signed-off by: Manfred Riem (manfred.riem@oracle.com)
=> Fixes issue #4423 - Enable javaee7 tests

.travis.yml
=> Fixes issue #4425 - Enable javaee6 tests

.travis.yml
=> Fixes issue #4427 - Enable servlet40 tests

.travis.yml
=> Fixes issue #4429 - Enable servlet31 tests

impl/pom.xml
(files are deleted immediately after)
=> Remove copy of files that has no effect.

api/pom.xml
=> #4473 - replaced ant based renderkit gen with maven plug-in

.gitignore, api/pom.xml, impl/pom-p.xml, impl/pom.xml, impl/src/main/java/javax/faces/component/search/package-info.java
=> Removed some lingering remnants of jsf-tools

impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/lifecycle/RestoreViewPhase.java, impl/src/main/java/javax/faces/application/ViewHandler.java
=> Fixes issue #4486 - Remove legacy JSF 1.2 view handler support

api/pom.xml, impl/pom-p.xml, pom.xml
=> Updating poms - formatting, organising and removing some 2.4 leftovers

test/servlet30/content-type/pom.xml
With previous value project cannot be even cleaned against fresh/empty Maven repo.
Signed-off-by: Piotrek Zygielo <piotr@zygielo.pl>
=> Fix version of parent

api/pom.xml, impl/pom.xml, jsf-tools/pom.xml, pom.xml, util/pom.xml
=> Removed usage of com.sun for maven coordinates, as this is not allowed.

api/pom.xml, impl/pom.xml, test/pom.xml, test/servlet30/facesContextInit/pom.xml
=> JSF tools set to optional dep, corrected versions of tools and API

api/pom.xml
=> Mojarra version for API build now taken from parent version.

api/pom.xml, impl/pom.xml, impl/src/main/java/javax/faces/component/UISelectMany.java, impl/src/main/java/javax/faces/webapp/UIComponentClassicTagBase.java, test/javaee6/correctScanningEar/pom.xml, test/osgi/simple/pom.xml
=> Fix compilation on Java 11

pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
=> Update parent pom to 1.0.5

api/pom.xml, impl/pom.xml, jsf-tools/pom.xml, pom.xml
=> Adopted Jakarta EE dependencies

impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java, impl/src/main/java/javax/faces/webapp/FacesServlet.java
#4525 CTS cherry picking from master branch
=> #4525 CTS cherry picking from master branch

impl/src/main/java/com/sun/faces/cdi/CdiUtils.java, test/javaee8/cdi/src/main/java/com/sun/faces/test/javaee8/cdi/BackingBean.java, test/javaee8/cdi/src/main/webapp/issue4500.xhtml
=> Fix for #4500

impl/src/main/java/com/sun/faces/application/ApplicationFactoryImpl.java
I see it was added intentionally in [javaserverfaces/mojarra](https://github.com/javaserverfaces/mojarra/commit/0129ffe2aa#diff-7c962b50d924954596ed4f8326d6c83aR88), but I'm not following the reason.
=> Remove unused code

CONTRIBUTING.md, README.md
=> Updated text files for Jakarta terms / coordinates

impl/src/main/java/com/sun/faces/el/ELUtils.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java, impl/src/test/java/com/sun/faces/el/ELUtilsTest.java, impl/src/test/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriterTest.java
=>  Escaping CDATA end tags and avoid NPE in addEL3_0_Resolvers

impl/src/main/java/com/sun/faces/renderkit/RenderKitImpl.java
This fixes a regression that is not present in master
Issue: https://github.com/eclipse-ee4j/mojarra/issues/4596
=> 4596 - Scripts with CDATA cause "empty response" error on Ajax render

test/bin/run-tests.sh
=> Servlet 3.0 (cactus) not needed in default test run.

README.md
=> Processing feedback - changed to Eclipse EE4J impl of Faces.

certifications/jakarta-faces/2.3/TCK-Results.md
=> Point product link to Mojarra website

impl/src/main/java/com/sun/faces/cdi/ViewScopeContextManager.java
=> Issue #4509 Removed faulty context map clear and replaced with check

impl/src/main/java/com/sun/faces/application/view/ViewScopeContextManager.java
Signed-off-by: David Matejcek <dmatej@seznam.cz>
=> Merged viewscope fix from master

certifications/jakarta-faces/2.3/TCK-Results.md
=> Updated with latest TCK results including SHA256

impl/src/main/java/com/sun/faces/cdi/CdiExtension.java, impl/src/main/java/com/sun/faces/cdi/CdiUtils.java
=> #4640 Add explicit Ids when addAnnotatedType is used

impl/src/main/java/com/sun/faces/facelets/tag/TagAttributeImpl.java, impl/src/test/java/com/sun/faces/facelets/tag/TestTagAttributeImpl.java
storing Expression infos in TagAttributeImpl
Signed-off-by: Kai Gülzau <kguelzau@novomind.com>
=> Fix #4082 Performance issue with ELUtils#isCompositeComponentMethodExprLookup

impl/src/main/java/javax/faces/component/UIInput.java
=> Fix breakage in UIInput

pom.xml
=> #4643 Update EE4J parent to 1.0.5

impl/pom.xml, pom.xml
=> Prepare for RC1 release

util/pom.xml
=> Also set util folder to RC1

impl/pom.xml, test/pom.xml, test/servlet30/facesContextInit/pom.xml
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
=> Spec and OSGi Import package version fix

impl/pom.xml, impl/src/test/java/com/sun/faces/util/ByteArrayGuardAESCTRTest.java, pom.xml, util/pom.xml
=> Prepare for RC2

impl/src/main/java/javax/faces/component/UIInput.java, impl/src/main/java/javax/faces/component/UIViewParameter.java, test/javaee6/viewParamNullValueAjax/pom.xml, test/javaee6/viewParamNullValueAjax/src/main/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/TestView.java, test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/beans.xml, test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/glassfish-web.xml, test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/web.xml, test/javaee6/viewParamNullValueAjax/src/main/webapp/viewparam-nullvalue-ajax.xhtml, test/javaee6/viewParamNullValueAjax/src/test/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/Issue4550IT.java, test/servlet31/faceletsEmptyAsNull/src/test/java/com/sun/faces/test/servlet31/faceletsemptyasnull/Issue2827IT.java
This is PR for 2.3 branch.
master branch PR is : https://github.com/eclipse-ee4j/mojarra/pull/4706
=> Issue4550 alternative 2.3

impl/pom.xml, impl/src/main/java/jakarta/faces/component/UIInput.java, impl/src/main/java/jakarta/faces/component/UIViewParameter.java, test/javaee6/viewParamNullValueAjax/pom.xml, test/javaee6/viewParamNullValueAjax/src/main/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/TestView.java, test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/beans.xml, test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/glassfish-web.xml, test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/web.xml, test/javaee6/viewParamNullValueAjax/src/main/webapp/viewparam-nullvalue-ajax.xhtml, test/javaee6/viewParamNullValueAjax/src/test/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/Issue4550IT.java, test/pom.xml, test/servlet30/facesContextInit/pom.xml, test/servlet31/faceletsEmptyAsNull/src/test/java/com/sun/faces/test/servlet31/faceletsemptyasnull/Issue2827IT.java
This is PR for 3.0 branch.
master branch PR is : https://github.com/eclipse-ee4j/mojarra/pull/4706
=> Issue4550 alternative 3.0

impl/src/main/java/com/sun/faces/util/Util.java
Commit
Signed-off-by: Moulali Shikalwadi <mshikalw@redhat.com>
PR for cherry-pick
=> [issue 4699] JSF trying to load DTD over the network

impl/pom.xml, pom.xml, util/pom.xml
=> Prepare for 3.0.0-RC3 release

impl/src/main/resources/META-INF/mojarra_ext.taglib.xml, impl/src/main/resources/com/sun/faces/facelets1_0-2_0toSchema.xsl, impl/src/main/resources/com/sun/faces/metadata/taglib/jstl-core.taglib.xml, impl/src/main/resources/com/sun/faces/metadata/taglib/jstl-fn.taglib.xml
=> #4737 More schema updates to jakartaee

impl/pom.xml, impl/src/main/java/com/sun/faces/application/applicationimpl/Version.java, impl/src/main/java/com/sun/faces/config/manager/tasks/ParseConfigResourceToDOMTask.java, impl/src/main/java/com/sun/faces/config/processor/FacesConfigNamespaceContext.java, impl/src/main/resources/META-INF/mojarra_ext.taglib.xml, impl/src/main/resources/com/sun/faces/facelets1_0-2_0toSchema.xsl, pom.xml, util/pom.xml
=> Namespace and version updates

impl/pom.xml, impl/src/main/javadoc/jakarta/faces/view/facelets/package.html, impl/src/main/resources/META-INF/error-include.xhtml, impl/src/main/resources/META-INF/html_basic.tld, impl/src/main/resources/META-INF/resources/jakarta.faces/jsf-uncompressed.js, impl/src/main/resources/com/sun/faces/metadata/taglib/composite.taglib.xml, impl/src/main/resources/com/sun/faces/metadata/taglib/facelets_jsf_core.taglib.xml, impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml, impl/src/main/resources/com/sun/faces/metadata/taglib/jstl-core.taglib.xml, impl/src/main/resources/com/sun/faces/standard-html-renderkit.xml, impl/src/main/resources/com/sun/faces/tlddoc-resources/tag.html.xsl
=> Lingering javax updates

impl/pom.xml, pom.xml, util/pom.xml
=> Prepare for RC5

impl/src/main/resources/META-INF/resources/jakarta.faces/jsf-uncompressed.js, impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml
=> Fixes for doc rendering

impl/pom.xml, pom.xml, util/pom.xml
=> Prepare for 3.0.0 release

impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java, impl/src/main/java/com/sun/faces/application/view/ViewHandlingStrategyManager.java, impl/src/main/java/com/sun/faces/config/ConfigManager.java, impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/config/processor/ApplicationConfigProcessor.java, impl/src/main/java/com/sun/faces/lifecycle/RestoreViewPhase.java, impl/src/main/java/jakarta/faces/application/ViewHandler.java
=> Remove legacy JSF 1.2 view handler support

impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java, impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java, impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/jakarta/faces/application/ViewHandler.java
=> Small refactoring of the viewhandler code after removal of JSP

impl/pom.xml
=> Make impl not depent on problematic parent

impl/pom.xml
=> Set full GAV for 3.0.0 release

impl/src/main/java/jakarta/faces/context/ExternalContext.java
=> #4784 Adjusted javadoc for managed bean removal

impl/src/main/java/com/sun/faces/config/manager/DbfFactory.java, impl/src/main/java/com/sun/faces/config/manager/FacesSchema.java, impl/src/main/java/com/sun/faces/config/manager/tasks/ParseConfigResourceToDOMTask.java, impl/src/main/java/com/sun/faces/config/processor/NavigationConfigProcessor.java, impl/src/main/resources/com/sun/faces/web-facesconfig_4_0.xsd
#4784 Add facesconfig xsd 4.0 which has managed bean tags removed
Updated parsing code to add this xsd, and refactored a bit.
=> #4784 Remove managed bean system - step 5

impl/src/main/java/com/sun/faces/push/WebsocketPushContext.java, impl/src/main/java/com/sun/faces/push/WebsocketSessionManager.java, impl/src/main/resources/META-INF/resources/javax.faces/jsf-uncompressed.js
https://github.com/eclipse-ee4j/mojarra/issues/4802
=> https://github.com/eclipse-ee4j/mojarra/issues/4802

impl/src/main/java/com/sun/faces/config/processor/FacesConfigNamespaceContext.java, impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java, impl/src/test/java/com/sun/faces/config/processor/FacesConfigNamespaceContextTest.java
Introduce a constructor to use given namespace instead of default
=> #4820 Faces 3.0 Does Not Support JavaEE NameSpace in Flow.xml Files

impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java, impl/src/test/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriterTest.java
=> Fix Exception in HtmlResponseWriter

impl/src/main/java/com/sun/faces/el/ELUtils.java
For now, this is the last patch in my series of patches for the customer situation I mentioned in pull request #4808. While analyzing the traces of the customer, I noticed that there are many thousand calls to `ELUtils.isCompositeComponentExpr()` that contribute measurably to the high amount of CPU consumption that the customer is currently experiencing.
When looking at `ELUtils.isCompositeComponentExpr()`, I found that all it basically does is regular expression matching. My proposed patch creates a small - 1000 entries at the moment - cache that stores the regular expression evaluation results for the incoming strings. In order to implement this cache, I used an admittedly very simple LRU cache based on a FIFO queue - see the `rememberEvaluationResult()` method in `ELUtils`.
Instead of …
=> Performance-optimized version of ELUtils.isCompositeComponentExpr()

impl/src/main/java/com/sun/faces/context/FacesContextImpl.java, impl/src/main/java/jakarta/faces/context/FacesContext.java
https://github.com/eclipse-ee4j/faces-api/issues/1557
=> Faces 4.0: Add FacesContext#getLifecycle()

impl/src/main/java/com/sun/faces/renderkit/html_basic/FileRenderer.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputFile.java, impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml
https://github.com/eclipse-ee4j/faces-api/issues/1555
=> Faces 4.0: h:inputFile multiple="true"

impl/src/main/java/jakarta/faces/component/UIComponent.java, impl/src/main/java/jakarta/faces/component/UIComponentBase.java
https://github.com/eclipse-ee4j/faces-api/issues/1558
=> Faces 4.0: make UIComponent#subscribeToEvent() more convenient

cdi/pom.xml, cdi/src/main/java/org/eclipse/mojarra/cdi/CdiLifecycleFactory.java, cdi/src/main/java/org/eclipse/mojarra/cdi/CdiRenderKitFactory.java, cdi/src/main/resources/META-INF/beans.xml, cdi/src/main/resources/META-INF/faces-config.xml, pom.xml
Deliver basic CDI support for some of the Faces factories
=> Fixes issue #4840 - Integrate CDI module

impl/src/main/java/jakarta/faces/context/FacesContextWrapper.java
https://github.com/eclipse-ee4j/faces-api/issues/1557
=> Add FacesContextWrapper#getLifeCycle()

impl/src/main/java/com/sun/faces/config/initfacescontext/NoOpFacesContext.java, impl/src/test/java/com/sun/faces/mock/MockFacesContext.java
https://github.com/eclipse-ee4j/mojarra/issues/4850
=> Implement new FacesContext#getLifeCycle

impl/pom.xml, test2/pom.xml, util/pom.xml
=> Update dependencies in pom.xml

impl/src/main/java/jakarta/faces/FacesException.java, impl/src/main/java/jakarta/faces/annotation/FacesConfig.java, impl/src/main/java/jakarta/faces/application/ProtectedViewException.java, impl/src/main/java/jakarta/faces/application/ResourceDependencies.java, impl/src/main/java/jakarta/faces/component/UIComponentBase.java, impl/src/main/java/jakarta/faces/component/UIForm.java, impl/src/main/java/jakarta/faces/component/UIViewParameter.java, impl/src/main/java/jakarta/faces/component/UIViewRoot.java, impl/src/main/java/jakarta/faces/component/behavior/AjaxBehavior.java, impl/src/main/java/jakarta/faces/component/behavior/FacesBehavior.java, impl/src/main/java/jakarta/faces/component/html/HtmlBody.java, impl/src/main/java/jakarta/faces/component/html/HtmlCommandButton.java, impl/src/main/java/jakarta/faces/component/html/HtmlCommandLink.java, impl/src/main/java/jakarta/faces/component/html/HtmlForm.java, impl/src/main/java/jakarta/faces/component/html/HtmlGraphicImage.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputFile.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputHidden.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputSecret.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputTextarea.java, impl/src/main/java/jakarta/faces/component/html/HtmlMessage.java, impl/src/main/java/jakarta/faces/component/html/HtmlPanelGrid.java, impl/src/main/java/jakarta/faces/component/html/HtmlPanelGroup.java, impl/src/main/java/jakarta/faces/component/html/HtmlSelectManyCheckbox.java, impl/src/main/java/jakarta/faces/component/html/HtmlSelectManyListbox.java, impl/src/main/java/jakarta/faces/component/html/HtmlSelectOneListbox.java, impl/src/main/java/jakarta/faces/component/html/HtmlSelectOneMenu.java, impl/src/main/java/jakarta/faces/component/html/HtmlSelectOneRadio.java, impl/src/main/java/jakarta/faces/context/FacesContext.java, impl/src/main/java/jakarta/faces/push/Push.java, impl/src/main/java/jakarta/faces/view/ViewDeclarationLanguageFactory.java
=> Fix several Javadoc errors and warnings

impl/pom.xml, test2/pom.xml
Added add-opens to surefire, since the mocking needs this now.
=> Set JDK target to JDK 11, and updated GlassFish used.

.travis.yml
=> Reduce travis build to compilation only

.github/workflows/build.yml, .travis.yml
=> Switch JDK to 11

impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java, test2/faces40/inputFile/pom.xml, test2/faces40/inputFile/src/main/java/com/sun/faces/test/servlet50/inputfile/Spec1555ITBean.java, test2/faces40/inputFile/src/main/webapp/WEB-INF/web.xml, test2/faces40/inputFile/src/main/webapp/spec1555IT.xhtml, test2/faces40/inputFile/src/test/java/com/sun/faces/test/servlet50/inputfile/Spec1555IT.java, test2/faces40/selectItemGroups/src/main/java/com/sun/faces/test/servlet50/selectitemgroups/Category.java, test2/faces40/selectItemGroups/src/main/java/com/sun/faces/test/servlet50/selectitemgroups/Product.java, test2/faces40/selectItemGroups/src/main/java/com/sun/faces/test/servlet50/selectitemgroups/Spec1559ITBean.java, test2/faces40/selectItemGroups/src/test/java/com/sun/faces/test/servlet50/selectitemgroups/Spec1559IT.java
https://github.com/eclipse-ee4j/faces-api/issues/1555
Also fixed some licence comments on the fly
=> Add IT for h:inputFile single/multiple

action/faces-config.NavData, action/pom.xml, action/src/main/java/org/eclipse/mojarra/action/ActionHeaderParameter.java, action/src/main/java/org/eclipse/mojarra/action/ActionInitializer.java, action/src/main/java/org/eclipse/mojarra/action/ActionLifecycle.java, action/src/main/java/org/eclipse/mojarra/action/ActionMapping.java, action/src/main/java/org/eclipse/mojarra/action/ActionMappingMatch.java, action/src/main/java/org/eclipse/mojarra/action/ActionMappingMatcher.java, action/src/main/java/org/eclipse/mojarra/action/ActionMappingParameter.java, action/src/main/java/org/eclipse/mojarra/action/ActionMappingType.java, action/src/main/java/org/eclipse/mojarra/action/ActionMethodExecutor.java, action/src/main/java/org/eclipse/mojarra/action/ActionParameterProducer.java, action/src/main/java/org/eclipse/mojarra/action/ActionPathParameter.java, action/src/main/java/org/eclipse/mojarra/action/ActionQueryParameter.java, action/src/main/java/org/eclipse/mojarra/action/ActionResponseHandler.java, action/src/main/java/org/eclipse/mojarra/action/DefaultActionMappingMatcher.java, action/src/main/java/org/eclipse/mojarra/action/DefaultActionMethodExecutor.java, action/src/main/java/org/eclipse/mojarra/action/DefaultActionParameterProducer.java, action/src/main/java/org/eclipse/mojarra/action/DefaultActionResponseHandler.java, action/src/main/resources/META-INF/beans.xml, action/src/main/resources/META-INF/faces-config.xml, action/src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer, pom.xml
Delivers an action based lifecycle for Faces
=> Fixes issue 4841 - Integrate Action module

README.md
=> Update Java version in readme

impl/src/main/java/com/sun/faces/renderkit/html_basic/TextRenderer.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputFile.java, impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml, test2/faces40/inputFile/src/main/webapp/spec1556IT.xhtml, test2/faces40/inputFile/src/test/java/com/sun/faces/test/servlet50/inputfile/Spec1556IT.java
https://github.com/eclipse-ee4j/faces-api/issues/1556
=> Add <h:inputFile accept>

test2/faces22/cdiMethodValidation/pom.xml, test2/faces22/cdiMethodValidation/src/main/java/com/sun/faces/test/javaee7/cdimethodvalidation/FooConstraint.java, test2/faces22/cdiMethodValidation/src/main/java/com/sun/faces/test/javaee7/cdimethodvalidation/FooConstraintValidator.java, test2/faces22/cdiMethodValidation/src/main/java/com/sun/faces/test/javaee7/cdimethodvalidation/HelloService.java, test2/faces22/cdiMethodValidation/src/main/java/com/sun/faces/test/javaee7/cdimethodvalidation/UserBean.java, test2/faces22/cdiMethodValidation/src/main/webapp/WEB-INF/beans.xml, test2/faces22/cdiMethodValidation/src/main/webapp/WEB-INF/web.xml, test2/faces22/cdiMethodValidation/src/main/webapp/index.xhtml, test2/faces22/cdiMethodValidation/src/test/java/com/sun/faces/test/javaee7/cdimethodvalidation/MethodValidationIT.java, test2/faces22/cdiMultiTenantSetsTccl/pom.xml, test2/faces22/cdiMultiTenantSetsTccl/src/main/java/com/sun/faces/test/javaee7/cdimultitenantsetstccl/BeforeFilter.java, test2/faces22/cdiMultiTenantSetsTccl/src/main/java/com/sun/faces/test/javaee7/cdimultitenantsetstccl/UserBean.java, test2/faces22/cdiMultiTenantSetsTccl/src/main/webapp/WEB-INF/web.xml, test2/faces22/cdiMultiTenantSetsTccl/src/main/webapp/index.xhtml, test2/faces22/cdiMultiTenantSetsTccl/src/test/java/com/sun/faces/test/javaee7/cdimultitenantsetstccl/Issue3341IT.java
=> Migrated two additional tests

impl/src/main/java/com/sun/faces/renderkit/AttributeManager.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/ButtonRenderer.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/OutcomeTargetButtonRenderer.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/TextRenderer.java, impl/src/main/java/jakarta/faces/component/html/HtmlCommandButton.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputFile.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputSecret.java, impl/src/main/java/jakarta/faces/component/html/HtmlOutcomeTargetButton.java, impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml
https://github.com/eclipse-ee4j/faces-api/issues/1562
=> Cleanup dangling attributes

impl/src/main/java/jakarta/faces/component/ComponentStateHelper.java
=> [#4821] Fix NPE in unit tests

test2/faces23/searchExpression/pom.xml, test2/faces23/searchExpression/src/main/java/com/sun/faces/test/javaee8/searchExpression/CustomSearchKeywordResolver.java, test2/faces23/searchExpression/src/main/java/com/sun/faces/test/javaee8/searchExpression/Spec1238.java, test2/faces23/searchExpression/src/main/webapp/WEB-INF/beans.xml, test2/faces23/searchExpression/src/main/webapp/WEB-INF/faces-config.xml, test2/faces23/searchExpression/src/main/webapp/WEB-INF/glassfish-web.xml, test2/faces23/searchExpression/src/main/webapp/WEB-INF/web.xml, test2/faces23/searchExpression/src/main/webapp/issue4331.xhtml, test2/faces23/searchExpression/src/main/webapp/spec1238.xhtml, test2/faces23/searchExpression/src/test/java/com/sun/faces/test/javaee8/searchExpression/Issue4331IT.java, test2/faces23/searchExpression/src/test/java/com/sun/faces/test/javaee8/searchExpression/Spec1238IT.java, test2/pom.xml
=> Migrated search expression test to Faces23

impl/src/main/java/com/sun/faces/facelets/tag/CompositeTagLibrary.java
https://github.com/eclipse-ee4j/mojarra/issues/4872
=> 2.3: getPrefixFromTag should return null when there is no prefix at all

impl/src/main/java/com/sun/faces/facelets/tag/CompositeTagLibrary.java
https://github.com/eclipse-ee4j/mojarra/issues/4872
=> 4.0: getPrefixFromTag should return null when there is no prefix at all

impl/src/main/resources/com/sun/faces/metadata/taglib/facelets_jsf_core.taglib.xml
https://github.com/eclipse-ee4j/faces-api/issues/1559
=> Add missing f:selectItemGroups attributes to taglib.xml

test2/faces23/websocket/.metadata/src/main/webapp/WEB-INF/faces-config.pageflow, test2/faces23/websocket/pom.xml, test2/faces23/websocket/src/main/java/com/sun/faces/test/javaee8/websocket/ConfigurationBean.java, test2/faces23/websocket/src/main/java/com/sun/faces/test/javaee8/websocket/Issue4332.java, test2/faces23/websocket/src/main/java/com/sun/faces/test/javaee8/websocket/Spec1396.java, test2/faces23/websocket/src/main/webapp/WEB-INF/beans.xml, test2/faces23/websocket/src/main/webapp/WEB-INF/faces-config.xml, test2/faces23/websocket/src/main/webapp/WEB-INF/web.xml, test2/faces23/websocket/src/main/webapp/issue4332.xhtml, test2/faces23/websocket/src/main/webapp/spec1396.xhtml, test2/faces23/websocket/src/main/webapp/spec1396EnableWebsocketEndpoint.xhtml, test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Issue4332IT.java, test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Spec1396IT.java
=> Migrated websocket test

test2/faces23/namespacedView/pom.xml, test2/faces23/namespacedView/src/main/java/com/sun/faces/test/javaee8/namespacedView/NamespacedView.java, test2/faces23/namespacedView/src/main/webapp/WEB-INF/beans.xml, test2/faces23/namespacedView/src/main/webapp/WEB-INF/faces-config.xml, test2/faces23/namespacedView/src/main/webapp/WEB-INF/web.xml, test2/faces23/namespacedView/src/main/webapp/spec790WithNamespacedView.xhtml, test2/faces23/namespacedView/src/main/webapp/spec790WithNamespacedViewAjaxNavigation.xhtml, test2/faces23/namespacedView/src/test/java/com/sun/faces/test/javaee8/namespacedView/Spec790WithNamespacedViewIT.java, test2/faces23/passthrough/pom.xml, test2/faces23/passthrough/src/main/webapp/WEB-INF/beans.xml, test2/faces23/passthrough/src/main/webapp/WEB-INF/faces-config.xml, test2/faces23/passthrough/src/main/webapp/WEB-INF/glassfish-web.xml, test2/faces23/passthrough/src/main/webapp/WEB-INF/web.xml, test2/faces23/passthrough/src/main/webapp/issue4093.xhtml, test2/faces23/passthrough/src/test/java/com/sun/faces/test/javaee8/passthrough/Issue4093IT.java, test2/faces23/websocket/pom.xml
=> Migrated namespacedview and passthrough tests to Faces23

test2/faces23/commandScript/pom.xml, test2/faces23/commandScript/src/main/java/com/sun/faces/test/javaee8/commandScript/ConfigurationBean.java, test2/faces23/commandScript/src/main/java/com/sun/faces/test/javaee8/commandScript/Spec613.java, test2/faces23/commandScript/src/main/webapp/WEB-INF/beans.xml, test2/faces23/commandScript/src/main/webapp/WEB-INF/faces-config.xml, test2/faces23/commandScript/src/main/webapp/WEB-INF/web.xml, test2/faces23/commandScript/src/main/webapp/spec613.xhtml, test2/faces23/commandScript/src/test/java/com/sun/faces/test/javaee8/commandScript/Spec613IT.java, test2/faces23/xhtmlMappingToFaceletByDefault/pom.xml, test2/faces23/xhtmlMappingToFaceletByDefault/src/main/java/com/sun/faces/test/javaee8/xhtmlmappingtofaceletbydefault/MyComponent.java, test2/faces23/xhtmlMappingToFaceletByDefault/src/main/webapp/WEB-INF/beans.xml, test2/faces23/xhtmlMappingToFaceletByDefault/src/main/webapp/index.xhtml, test2/faces23/xhtmlMappingToFaceletByDefault/src/main/webapp/withoutxmlprolog.xhtml, test2/faces23/xhtmlMappingToFaceletByDefault/src/test/java/com/sun/faces/test/javaee8/xhtmlmappingtofaceletbydefault/XhtmlMappingToFaceletIT.java
=> Migrated commandscript and xhtmlbydefault tests to Faces23

impl/src/main/java/com/sun/faces/renderkit/AttributeManager.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/TextRenderer.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputText.java, impl/src/main/resources/com/sun/faces/metadata/taglib/html_basic.taglib.xml, test2/faces40/inputText/pom.xml, test2/faces40/inputText/src/main/webapp/WEB-INF/web.xml, test2/faces40/inputText/src/main/webapp/spec1560IT.xhtml, test2/faces40/inputText/src/test/java/com/sun/faces/test/servlet50/inputtext/Spec1560IT.java
https://github.com/eclipse-ee4j/faces-api/issues/1560
=> Add h:inputText type

impl/src/main/java/jakarta/faces/annotation/ManagedProperty.java
https://github.com/eclipse-ee4j/faces-api/issues/1470
=> Explicitly state that ManagedProperty requires FacesContext

impl/src/main/java/com/sun/faces/application/view/ViewMetadataImpl.java, impl/src/main/java/com/sun/faces/context/UrlBuilder.java, impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java
=> Backport #4727/#4503/#4830 to 2.3

impl/src/main/java/com/sun/faces/application/view/ViewMetadataImpl.java, impl/src/main/java/com/sun/faces/context/UrlBuilder.java, impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java
=> Backport #4727/#4503/#4830 to 3.0

impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/4649
=> Fix unnecessary session creation during ExternalContext#redirect()

impl/src/main/java/com/sun/faces/el/ELUtils.java
already merged 2.3-PR: https://github.com/eclipse-ee4j/mojarra/pull/4810
=> Performance-optimized version of ELUtils.isCompositeComponentExpr() (ported to 3.0)

impl/src/main/java/com/sun/faces/el/ELUtils.java
already merged 2.3-PR: https://github.com/eclipse-ee4j/mojarra/pull/4810
=> Performance-optimized version of ELUtils.isCompositeComponentExpr() (ported to 4.0 / master)

impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java
already merged 2.3 - PR: #4809
=> Performance-optimized version of ResourceImpl.getURL() (ported to 3.0)

impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java
already merged 2.3 - PR: https://github.com/eclipse-ee4j/mojarra/pull/4809
=> Performance-optimized version of ResourceImpl.getURL() (ported to 4.0 / master)

impl/src/main/java/jakarta/faces/component/ComponentStateHelper.java, impl/src/main/java/jakarta/faces/component/UIComponentBase.java
Signed-off-by: Christoph Straßer christoph.strasser78@gmail.com
=> #4881 Empty lists are discarded during state-saving (ported to 3.0)

impl/src/main/java/com/sun/faces/application/view/FaceletPartialStateManagementStrategy.java, impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java, impl/src/main/java/javax/faces/component/visit/VisitHint.java, test/servlet30/dynamic/src/main/webapp/add_uirepeat.xhtml, test/servlet30/dynamic/src/test/java/com/sun/faces/test/servlet30/dynamic/Issue4261IT.java
https://github.com/eclipse-ee4j/mojarra/issues/4261
=> issue 4261 - Fix dynamic components in uirepeat with ajax from uirepeat row

impl/src/main/java/com/sun/faces/application/view/FaceletFullStateManagementStrategy.java, impl/src/main/java/com/sun/faces/application/view/FaceletPartialStateManagementStrategy.java, impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java, impl/src/main/java/com/sun/faces/context/StateContext.java, impl/src/main/java/com/sun/faces/util/ComponentStruct.java, test/servlet30/dynamic/src/main/java/com/sun/faces/test/servlet30/dynamic/Issue4664Bean.java, test/servlet30/dynamic/src/main/java/com/sun/faces/test/servlet30/dynamic/Issue4664Component.java, test/servlet30/dynamic/src/main/webapp/WEB-INF/issue4664.taglib.xml, test/servlet30/dynamic/src/main/webapp/WEB-INF/web.xml, test/servlet30/dynamic/src/main/webapp/issue4664.xhtml, test/servlet30/dynamic/src/main/webapp/removeComponent.xhtml, test/servlet30/dynamic/src/test/java/com/sun/faces/test/servlet30/dynamic/Issue4664IT.java
#4664 
Signed-off-by: gndrm <andreas.gundrum11@gmail.com>
=> Fixed dynamic remove of facets

impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/facelets/impl/DefaultFacelet.java, impl/src/main/java/com/sun/faces/facelets/impl/DefaultFaceletFactory.java, test/servlet31/faceletsID/pom.xml, test/servlet31/faceletsID/src/main/java/com/sun/faces/test/servlet31/faceletsID/TestBean.java, test/servlet31/faceletsID/src/main/webapp/WEB-INF/web.xml, test/servlet31/faceletsID/src/main/webapp/index.xhtml, test/servlet31/faceletsID/src/test/java/com/sun/faces/test/servlet31/faceletsID/FaceletIDITCase.java
https://github.com/eclipse-ee4j/mojarra/issues/4677
https://github.com/eclipse-ee4j/mojarra/pull/4695
=> Backport https://github.com/eclipse-ee4j/mojarra/pull/4695/files to 2.3

impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java, impl/src/main/java/com/sun/faces/facelets/compiler/SAXCompiler.java, impl/src/main/java/com/sun/faces/facelets/impl/DefaultFacelet.java, impl/src/main/java/com/sun/faces/facelets/impl/DefaultFaceletFactory.java, impl/src/main/java/com/sun/faces/facelets/impl/XMLFrontMatterSaver.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/DoctypeRenderer.java, impl/src/main/java/com/sun/faces/util/Util.java, impl/src/main/java/jakarta/faces/component/Doctype.java, impl/src/main/java/jakarta/faces/component/UIViewRoot.java, impl/src/main/java/jakarta/faces/component/html/HtmlDoctype.java, test2/faces40/doctype/pom.xml, test2/faces40/doctype/src/main/webapp/WEB-INF/faces-config.xml, test2/faces40/doctype/src/main/webapp/WEB-INF/web.xml, test2/faces40/doctype/src/main/webapp/spec1568IT-HTML4-public.xhtml, test2/faces40/doctype/src/main/webapp/spec1568IT-HTML4-system.xhtml, test2/faces40/doctype/src/main/webapp/spec1568IT-HTML5.xhtml, test2/faces40/doctype/src/test/java/com/sun/faces/test/servlet50/doctype/Spec1568IT.java
https://github.com/eclipse-ee4j/faces-api/issues/1568
=> Faces 4.0: add UIViewRoot#getDoctype()

impl/src/main/java/com/sun/faces/facelets/tag/jsf/ComponentSupport.java, impl/src/main/java/javax/faces/component/ComponentStateHelper.java, impl/src/main/java/javax/faces/component/UIComponent.java, impl/src/main/java/javax/faces/component/UIComponentBase.java
https://github.com/eclipse-ee4j/mojarra/issues/4811
=> Move logic from UIComponent to ComponentSupport

impl/src/main/java/com/sun/faces/application/resource/ClientResourceInfo.java, impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java, impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java, impl/src/main/java/com/sun/faces/facelets/tag/faces/core/AjaxHandler.java, impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java, impl/src/main/java/jakarta/faces/application/ResourceHandler.java
https://github.com/eclipse-ee4j/faces-api/issues/1552
=> Rename ResourceHandler constants

impl/src/main/java/com/sun/faces/application/view/ViewScopeContextManager.java, impl/src/main/java/com/sun/faces/application/view/ViewScopeManager.java, test/javaee7/cdiInitDestroyEvent/src/main/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/ViewScopedBean.java, test/javaee7/cdiInitDestroyEvent/src/main/webapp/issue4646.xhtml, test/javaee7/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue4646IT.java
Backport of issue #4646 for the current 2.3 branch. Plain cherry pick done from the commit. Test checked with a glassfish 5.1.
=> [Issue 4646] [branch 2.3] @PreDestroy not called all the times on view scoped using CDI

impl/src/main/java/com/sun/faces/application/view/ViewScopeContextManager.java, impl/src/main/java/com/sun/faces/application/view/ViewScopeManager.java, test/javaee7/cdiInitDestroyEvent/src/main/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/ViewScopedBean.java, test/javaee7/cdiInitDestroyEvent/src/main/webapp/issue4646.xhtml, test/javaee7/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue4646IT.java
Backport of issue #4646 for the 3.0 branch. Minor modifications needed to accommodate the commit. Tests seems to be disabled right now, so the test part was not modified.
=> [Issue 4646] [branch 3.0] @PreDestroy not called all the times on view scoped using CDI

impl/src/main/java/com/sun/faces/facelets/tag/composite/AttachedObjectTargetImpl.java, impl/src/main/java/com/sun/faces/facelets/tag/composite/BehaviorHolderAttachedObjectTargetImpl.java, impl/src/main/java/com/sun/faces/facelets/tag/composite/BehaviorHolderWrapper.java, impl/src/main/java/com/sun/faces/facelets/tag/jsf/core/AjaxHandler.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
https://github.com/eclipse-ee4j/faces-api/issues/1567
This is a backport of https://github.com/eclipse-ee4j/mojarra/pull/4911/files for 2.3
=> Backport f:ajax execute/render=@this in composite to 2.3; all tests passed localhost

impl/src/main/java/com/sun/faces/facelets/tag/composite/AttachedObjectTargetImpl.java, impl/src/main/java/com/sun/faces/facelets/tag/composite/BehaviorHolderAttachedObjectTargetImpl.java, impl/src/main/java/com/sun/faces/facelets/tag/composite/BehaviorHolderWrapper.java, impl/src/main/java/com/sun/faces/facelets/tag/faces/core/AjaxHandler.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java, impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml, test2/faces40/ajax/pom.xml, test2/faces40/ajax/src/main/java/org/glassfish/mojarra/faces40/ajax/Spec1567ITBean.java, test2/faces40/ajax/src/main/webapp/WEB-INF/web.xml, test2/faces40/ajax/src/main/webapp/resources/components/component.xhtml, test2/faces40/ajax/src/main/webapp/spec1567IT.xhtml, test2/faces40/ajax/src/test/java/com/sun/faces/test/servlet50/ajax/Spec1567IT.java
https://github.com/eclipse-ee4j/faces-api/issues/1567
=> Improve f:ajax execute/render interpretation of relative IDs when nested in composite component

impl/src/main/java/com/sun/faces/cdi/CdiUtils.java, test/javaee8/cdi/src/main/java/com/sun/faces/test/javaee8/cdi/Issue4913Converter.java, test/javaee8/cdi/src/main/webapp/issue4913.xhtml, test/javaee8/cdi/src/main/webapp/resources/issue4913ResourceDependency.js, test/javaee8/cdi/src/test/java/com/sun/faces/test/javaee8/cdi/Issue4913IT.java
https://github.com/eclipse-ee4j/mojarra/issues/4913
=> Mojarra 2.3: @ResourceDependency is not injected in @FacesConverter when managed=true

impl/src/main/java/com/sun/faces/flow/FlowDiscoveryCDIExtension.java
https://github.com/eclipse-ee4j/mojarra/issues/4916
=> Fix WELD warning about usage of deprecated CDI method

impl/src/main/java/com/sun/faces/facelets/impl/DefaultFaceletFactory.java
https://github.com/eclipse-ee4j/mojarra/issues/4912
=> Fix memory leak in ViewDeclarationLanguage#createComponent() impl

pom.xml
=> Update Eclipse parent pom to 1.0.6

impl/src/main/java/com/sun/faces/context/FacesContextFactoryImpl.java, impl/src/main/java/jakarta/faces/component/UIComponent.java, impl/src/test/java/jakarta/faces/component/UIComponentBaseTestCase.java
https://github.com/eclipse-ee4j/faces-api/issues/1571
=> Faces 4.0: remove deprecated "current component" constants from UIComponent

impl/src/main/java/com/sun/faces/facelets/tag/jsf/ComponentSupport.java, impl/src/main/java/javax/faces/component/ComponentStateHelper.java, impl/src/main/java/javax/faces/component/UIComponent.java, impl/src/main/java/javax/faces/component/UIComponentBase.java
Ran TCK against this branch, it passed successfully, so it was indeed the cause.
=> Revert #4808 due to being possible cause of failing TCK

impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java
=> #4925 - Guard for empty strings in html response writer

test/javaee8/ajax/src/main/java/com/sun/faces/test/javaee8/ajax/Issue4925.java, test/javaee8/ajax/src/main/webapp/issue4925.xhtml, test/javaee8/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Issue49251IT.java
#4925 Correctly fails on 2.3.15, passes on 2.3.16-SNAPSHOT.
=> #4925 - Provide test for #4925 Exception when writing partial response

test2/README.md, test2/faces22/childCountTest/pom.xml, test2/faces22/childCountTest/src/main/java/com/sun/faces/test/javaee7/childCountTest/TestServlet.java, test2/faces22/childCountTest/src/main/webapp/WEB-INF/beans.xml, test2/faces22/childCountTest/src/main/webapp/WEB-INF/web.xml, test2/faces22/childCountTest/src/test/java/com/sun/faces/test/javaee7/childCountTest/ChildCountTestIT.java, test2/pom.xml
=> Added test for child counting in components.

impl/src/main/java/com/sun/faces/config/WebConfiguration.java
=> #4923: deprecate com.sun.faces.enableRestoreView11Compatibility

impl/src/main/java/com/sun/faces/util/Util.java
=> Fix #4933: use CDI#getBeanManager() as fallback to get BeanManager

impl/src/main/java/com/sun/faces/renderkit/html_basic/RadioRenderer.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/SelectManyCheckboxListRenderer.java, impl/src/main/java/jakarta/faces/component/html/HtmlSelectManyCheckbox.java, impl/src/main/java/jakarta/faces/component/html/HtmlSelectOneRadio.java, impl/src/main/resources/com/sun/faces/metadata/taglib/faces.html.taglib.xml, test2/faces40/selectManyCheckbox/pom.xml, test2/faces40/selectManyCheckbox/src/main/java/com/sun/faces/test/servlet50/selectmanycheckbox/Category.java, test2/faces40/selectManyCheckbox/src/main/java/com/sun/faces/test/servlet50/selectmanycheckbox/Product.java, test2/faces40/selectManyCheckbox/src/main/java/com/sun/faces/test/servlet50/selectmanycheckbox/Spec1574ITBean.java, test2/faces40/selectManyCheckbox/src/main/webapp/WEB-INF/web.xml, test2/faces40/selectManyCheckbox/src/main/webapp/spec1574IT.xhtml, test2/faces40/selectManyCheckbox/src/test/java/com/sun/faces/test/servlet50/selectmanycheckbox/Spec1574IT.java
https://github.com/eclipse-ee4j/faces-api/issues/1574
=> h:selectManyCheckbox/h:selectOneRadio layout="list"

impl/src/main/java/jakarta/faces/component/UIComponentBase.java
=> Fix #4936: Defensive array checks

impl/src/main/java/com/sun/faces/cdi/CdiProducer.java, impl/src/main/java/com/sun/faces/push/WebsocketSessionManager.java, impl/src/main/java/com/sun/faces/util/cdi11/CDIUtilImpl.java
A 3.0 counterpart of https://github.com/eclipse-ee4j/mojarra/pull/4943
See the above PR for details.
=> CDI - Replace deprecated API usages.

impl/src/main/java/com/sun/faces/renderkit/html_basic/WebsocketRenderer.java, impl/src/main/java/jakarta/faces/component/UIWebsocket.java, impl/src/main/java/jakarta/faces/push/Push.java, impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js, impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml, impl/src/main/resources/com/sun/faces/standard-html-renderkit.xml
https://github.com/eclipse-ee4j/faces-api/issues/1573
=> Add <f:websocket onerror>

impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java, test2/faces40/namespaces/src/main/webapp/spec1553IT.xhtml, test2/faces40/namespaces/src/test/java/com/sun/faces/test/servlet50/namespaces/Spec1553IT.java
https://github.com/eclipse-ee4j/mojarra/issues/4949
=> Spec1423IT failing since #1553

impl/src/main/java/jakarta/faces/convert/DateTimeConverter.java, test2/faces23/converter/pom.xml, test2/faces23/converter/src/main/java/com/sun/faces/test/javaee8/converter/BackingBean.java, test2/faces23/converter/src/main/webapp/Issue4070InputOutputDiffer.xhtml, test2/faces23/converter/src/main/webapp/Issue4070Using.xhtml, test2/faces23/converter/src/main/webapp/WEB-INF/faces-config.xml, test2/faces23/converter/src/main/webapp/WEB-INF/web.xml, test2/faces23/converter/src/main/webapp/index.xhtml, test2/faces23/converter/src/main/webapp/issue4087.xhtml, test2/faces23/converter/src/main/webapp/issue4110.xhtml, test2/faces23/converter/src/test/java/com/sun/faces/test/javaee8/converter/Issue4070IT.java, test2/faces23/converter/src/test/java/com/sun/faces/test/javaee8/converter/Issue4087IT.java, test2/faces23/converter/src/test/java/com/sun/faces/test/javaee8/converter/Issue4110IT.java, test2/faces23/pom.xml, test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Spec1396IT.java
=> Add converter tests for Faces 2.3 to test2

test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Spec1396IT.java
=> Revert timing changes - makes no difference

impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java, impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java, impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java, impl/src/main/java/com/sun/faces/application/view/ViewHandlingStrategy.java, impl/src/main/java/com/sun/faces/util/Util.java, test2/faces22/protectedView/src/test/java/com/sun/faces/test/javaee7/protectedview/Bug22995287IT.java
=> #4955 Adopt Servlet 4 mapping API

impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java, impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java, impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java, impl/src/main/java/com/sun/faces/application/view/ViewMetadataImpl.java, impl/src/main/java/com/sun/faces/facelets/impl/DefaultFaceletFactory.java, impl/src/main/java/com/sun/faces/lifecycle/RestoreViewPhase.java, impl/src/main/java/jakarta/faces/application/ViewHandler.java
Removed empty lines, renamed variables.
=> Some code cleaning

impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java, impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/renderkit/ServerSideStateHelper.java
https://github.com/eclipse-ee4j/mojarra/issues/4965
=> Remove support for long-deprecated context params

impl/src/main/java/com/sun/faces/facelets/tag/jsf/IterationIdManager.java
=> Fix #4930: 2.3 IterationManager double checked lock idiom

impl/pom.xml, pom.xml, test/pom.xml, util/pom.xml
Effectively sets the version to 2.3.17-SNAPSHOT
=> Merge 2.3.16 release branch into 2.3

impl/src/main/java/com/sun/faces/facelets/tag/faces/IterationIdManager.java
=> Fix #4930: 4.0 IterationManager double checked lock idiom

.github/workflows/build.yml, impl/pom.xml, impl/src/main/java/com/sun/faces/application/ViewHandlerResponseWrapper.java, impl/src/test/java/com/sun/faces/mock/MockHttpServletRequest.java, impl/src/test/java/com/sun/faces/mock/MockHttpServletResponse.java, impl/src/test/java/com/sun/faces/mock/MockHttpSession.java
https://github.com/eclipse-ee4j/faces-api/issues/1586
=> Faces 4.0: bump Servlet API dependency from 5.0.0 to 6.0.0

impl/src/main/java/jakarta/faces/component/behavior/FacesBehavior.java, impl/src/main/java/jakarta/faces/validator/FacesValidator.java
=> Issue #4389: Update FacesValidator and FacesBehavior Target

action/pom.xml, cdi/pom.xml, impl/pom.xml, pom.xml, rest/pom.xml, test2/faces22/viewScope/pom.xml, test2/pom.xml, test2/util/pom.xml, util/pom.xml
=> Update versions in pom, mainly to EE 10 versions

impl/src/main/java/com/sun/faces/RIConstants.java, impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java, impl/src/main/java/com/sun/faces/config/FacesInitializer.java, impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/util/Util.java, impl/src/main/java/jakarta/faces/webapp/FacesServlet.java, test2/faces40/extensionless-mapping/pom.xml, test2/faces40/extensionless-mapping/src/main/java/org/javaee8/cdi/dynamic/bean/ApplicationInit.java, test2/faces40/extensionless-mapping/src/main/webapp/WEB-INF/web.xml, test2/faces40/extensionless-mapping/src/main/webapp/bar.xhtml, test2/faces40/extensionless-mapping/src/main/webapp/foo.xhtml, test2/faces40/extensionless-mapping/src/main/webapp/sub/bar.xhtml, test2/faces40/extensionless-mapping/src/test/java/org/javaee8/cdi/dynamic/bean/ExtensionlessMappingIT.java, test2/faces40/extensionless-mapping/src/test/resources/beans.xml, test2/faces40/pom.xml
Mojarra implementation of https://github.com/eclipse-ee4j/faces-api/issues/1508
=> Spec 1508 - Implement automatic extensionless mapping

test2/faces22/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue2948IT.java, test2/faces22/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue2997IT.java, test2/faces22/cdiInitDestroyEvent/src/test/java/com/sun/faces/test/javaee7/cdiinitdestroyevent/Issue4646IT.java, test2/faces22/cdiMethodValidation/src/test/java/com/sun/faces/test/javaee7/cdimethodvalidation/MethodValidationIT.java, test2/faces22/cdiMultiTenantSetsTccl/src/test/java/com/sun/faces/test/javaee7/cdimultitenantsetstccl/Issue3341IT.java, test2/faces22/cdiNoBeansXml/src/test/java/com/sun/faces/test/javaee7/cdinobeansxml/NoBeansXmlIT.java, test2/faces22/expressionLanguageLambda/src/test/java/com/sun/faces/test/javaee7/el/BasicLambdaIT.java, test2/faces22/multiFieldValidation/src/test/java/com/sun/faces/test/javaee7/multiFieldValidation/Spec1IT.java, test2/faces22/viewActionCdiViewScoped/src/test/java/com/sun/faces/test/javaee7/viewActionCdiViewScoped/ViewActionCdiViewScopedIT.java, test2/faces22/viewParamNullValueAjax/src/test/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/Issue4550IT.java, test2/faces22/viewScope/src/test/java/com/sun/faces/test/javaee6web/viewscope/Issue2641IT.java, test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Issue3981IT.java, test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Issue4115IT.java, test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Spec1412IT.java, test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Spec1423IT.java, test2/faces23/cdi/src/test/java/com/sun/faces/test/javaee8/cdi/Issue4551IT.java, test2/faces23/commandScript/src/test/java/com/sun/faces/test/javaee8/commandScript/Spec613IT.java, test2/faces23/faceletCacheFactory/src/test/java/com/sun/faces/test/servlet40/faceletCacheFactory/Issue3755IT.java, test2/faces23/facesConverter/src/test/java/com/sun/faces/test/javaee8/facesConverter/Issue4913IT.java, test2/faces23/passthrough/src/test/java/com/sun/faces/test/javaee8/passthrough/Issue4093IT.java, test2/faces23/validateWholeBean/src/test/java/com/sun/faces/test/javaee8/validateWholeBean/Issue4083IT.java, test2/faces23/validateWholeBean/src/test/java/com/sun/faces/test/javaee8/validateWholeBean/Issue4313IT.java, test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Spec1396IT.java, test2/faces40/ajax/src/test/java/com/sun/faces/test/servlet50/ajax/Spec1567IT.java, test2/faces40/inputFile/src/test/java/com/sun/faces/test/servlet50/inputfile/Spec1555IT.java, test2/faces40/inputText/src/test/java/com/sun/faces/test/servlet50/inputtext/Spec1560IT.java, test2/faces40/namespaces/src/test/java/com/sun/faces/test/servlet50/namespaces/Spec1553IT.java, test2/faces40/selectItemGroup/src/test/java/com/sun/faces/test/servlet50/selectitemgroup/Spec1563IT.java, test2/faces40/selectItemGroups/src/test/java/com/sun/faces/test/servlet50/selectitemgroups/Spec1559IT.java
=> Change asText to asNormalizedText as per deprecation notice

test2/pom.xml
=> Update Arquillian plug-in to latest for GF, and GF to 6.2.3

impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java, impl/src/main/java/com/sun/faces/context/PartialViewContextImpl.java, impl/src/main/java/com/sun/faces/context/flash/ELFlash.java
https://github.com/eclipse-ee4j/mojarra/issues/4977
=> Flash doPostPhaseActions() should be done before endDocument()

impl/src/main/java/com/sun/faces/config/manager/FacesSchema.java, impl/src/main/resources/com/sun/faces/jakartaee_10.xsd, impl/src/main/resources/com/sun/faces/web-facelettaglibrary_4_0.xsd, impl/src/main/resources/com/sun/faces/web-facesconfig_4_0.xsd, impl/src/main/resources/com/sun/faces/web-partialresponse_4_0.xsd
- Added jakartaee_10.xsd from https://jakarta.ee/xml/ns/jakartaee/jakartaee_10.xsd
- Added web-facelettaglibrary_4_0.xsd
- Added web-partialresponse_4_0.xsd
- Updated web-facesconfig_4_0.xsd
- Catch up FacesSchema
=> Add missing XSDs

impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java, impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
=> Pushbuilder is now in the minimum Servlet API. No need for tricks.

impl/src/main/java/com/sun/faces/RIConstants.java, impl/src/main/java/com/sun/faces/config/manager/Documents.java, impl/src/main/java/com/sun/faces/config/manager/tasks/ParseConfigResourceToDOMTask.java, impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java, impl/src/main/java/com/sun/faces/util/Util.java, impl/src/main/java/jakarta/faces/application/ApplicationConfigurationPopulator.java
For internal parsing/population of config files.
=> Bump XML namespace to Jakarta EE

impl/src/main/java/com/sun/faces/RIConstants.java, impl/src/main/java/com/sun/faces/config/manager/Documents.java, impl/src/main/java/com/sun/faces/config/manager/FacesSchema.java, impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java, impl/src/main/resources/com/sun/faces/jakartaee_10.xsd, impl/src/main/resources/com/sun/faces/web-facelettaglibrary_4_0.xsd, impl/src/main/resources/com/sun/faces/web-facesconfig_4_0.xsd, impl/src/main/resources/com/sun/faces/web-partialresponse_4_0.xsd
Also took the opportunity to add missing schemas for JEE10/Faces4
=> Fix failing tests caused by changes in faces schemas

test2/pom.xml
=> Update GlassFish to 7.0.0-M2

impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java, impl/src/main/java/com/sun/faces/util/Util.java, impl/src/main/java/javax/faces/component/UIData.java
https://github.com/eclipse-ee4j/mojarra/issues/4957
=> Improve detection of iterable parents in ui:repeat and h:dataTable

impl/src/main/java/com/sun/faces/facelets/tag/composite/InsertChildrenHandler.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java, test2/faces40/ajax/src/main/webapp/issue5032IT.xhtml, test2/faces40/ajax/src/main/webapp/resources/components/wrapper.xhtml, test2/faces40/ajax/src/test/java/com/sun/faces/test/servlet50/ajax/Issue5032IT.java
https://github.com/eclipse-ee4j/mojarra/issues/5032
=> Fix f:ajax @this behavior in composite when inserted via cc:insertChildren

impl/src/main/java/com/sun/faces/facelets/tag/composite/InsertChildrenHandler.java, impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
https://github.com/eclipse-ee4j/mojarra/issues/5032
=> Backport #5032 for 2.3

impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java, impl/src/main/java/com/sun/faces/util/HtmlUtils.java, impl/src/test/java/com/sun/faces/util/TestHtmlUtils.java, test/javaee8/ajax/src/main/java/com/sun/faces/test/javaee8/ajax/Issue5036.java, test/javaee8/ajax/src/main/webapp/issue5036.xhtml, test/javaee8/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Issue5036IT.java, test/servlet30/renderKit/src/main/java/com/sun/faces/test/servlet30/renderkit/CustomResponseWriter.java, test/servlet30/systest/src/main/java/com/sun/faces/systest/render/CustomResponseWriter.java
https://github.com/eclipse-ee4j/mojarra/issues/5036
=> Fix ajax error when form feed char is present in partial response

test2/faces40/ajax/src/main/java/org/glassfish/mojarra/faces40/ajax/Issue5036ITBean.java, test2/faces40/ajax/src/main/webapp/issue5036IT.xhtml, test2/faces40/ajax/src/test/java/com/sun/faces/test/servlet50/ajax/Issue5036IT.java
Reimplement integration test of https://github.com/eclipse-ee4j/mojarra/pull/5037 for master
=> https://github.com/eclipse-ee4j/mojarra/issues/5036

impl/src/main/java/com/sun/faces/util/Util.java
https://github.com/eclipse-ee4j/mojarra/issues/5041
=> #5041 fix deploy fail when optionally injectable class is not injectable

impl/src/main/java/com/sun/faces/config/FacesInitializer.java, impl/src/main/java/com/sun/faces/config/FacesInitializer2.java, impl/src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
=> Fix faces startup by moving the resource annotation to a different init.

impl/pom.xml, rest/pom.xml
=> Update CDI to 4.0.0

action/pom.xml, cdi/pom.xml, impl/pom.xml, rest/pom.xml
=> Update versions in poms

impl/src/main/java/com/sun/faces/config/ConfigureListener.java
see https://github.com/eclipse-ee4j/mojarra/issues/5061
=> Remove redundant JSP checks

impl/src/main/java/com/sun/faces/application/resource/ResourceCache.java, impl/src/main/java/com/sun/faces/config/ConfigureListener.java, impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
forward port of #5064 into 3.0
=> Remove checks for Servlet < 3.0

impl/src/main/java/com/sun/faces/facelets/tag/jsf/ComponentSupport.java
https://github.com/eclipse-ee4j/mojarra/issues/5073
=> Restore original impl of findChildByTagId() for the FSS case

impl/src/main/java/jakarta/faces/component/UISelectMany.java
=> Fix merge error

README.md, certifications/jakarta-faces/4.0/TCK-Results.md
=> Update SHA and readme

certifications/jakarta-faces/4.0/TCK-Results.md
=> Update javatest to correct number from rerun

certifications/jakarta-faces/4.0/TCK-Results.md
=> Update SHA in test results as well.

impl/src/main/java/jakarta/faces/component/ComponentStateHelper.java, impl/src/test/java/jakarta/faces/component/UIComponentBaseTestCase.java
=> Fix #5059: Backport for 3.0 FACELETS_REFRESH_PERIOD > 0

impl/src/main/java/javax/faces/component/ComponentStateHelper.java, impl/src/test/java/javax/faces/component/UIComponentBaseTestCase.java
=> Fix #5059: Backport for 2.3 FACELETS_REFRESH_PERIOD > 0

impl/src/main/java/javax/faces/component/UIForm.java
=> Fix #5097: UIForm performance improvement 2.3

impl/src/main/java/jakarta/faces/component/UIForm.java
=> Fix #5097: UIForm performance improvement 3.0

impl/src/main/java/jakarta/faces/component/UIForm.java
=> Fix #5097: UIForm performance improvement 4.0

impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java
=> Do not log ClientAbortException - 3.0

impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java
=> Do not log ClientAbortException - 4.0

impl/src/main/java/com/sun/faces/cdi/CdiUtils.java
https://github.com/eclipse-ee4j/mojarra/issues/5075
=> Fix #5075: add support to CDI-resolve @FacesValidator without ID

impl/src/main/java/jakarta/faces/component/AttachedObjectListHolder.java
=> Fix #4260: AttachedObjectListHolder IndexOutOfBounds fix 4.0

impl/src/main/java/com/sun/faces/facelets/compiler/CompilationManager.java
https://github.com/eclipse-ee4j/mojarra/issues/4281
=> Fix #4281: corrupted component tree when using namespaced HTML elements

impl/src/main/java/javax/faces/component/AttachedObjectListHolder.java
=> Fix #4260: AttachedObjectListHolder IndexOutOfBounds fix 2.3

impl/src/main/java/com/sun/faces/el/ELUtils.java
compositeComponentEvaluationCacheMaxSize variable is a private static final.
=> ELUtils - remove dead code

impl/src/test/java/com/sun/faces/xml/ParseXMLTestCase.java
* Removed "obvious" comments
* Imports clean-up
* Removed unused function
* Removed code that is commented out
* Removed unused jsfri variable
=> ParseXMLTestCase - clean-up

impl/src/main/java/com/sun/faces/application/resource/WebappResourceHelper.java, impl/src/main/java/com/sun/faces/util/Util.java
https://github.com/eclipse-ee4j/mojarra/issues/5118
=> #5118: ensure that leading slash is present on result of context params WEBAPP_RESOURCES_DIRECTORY and WEBAPP_CONTRACTS_DIRECTORY

impl/src/test/java/jakarta/faces/component/UIComponentTestCase.java
* Removed unused fragments
* Add raw types
* Remove checking of ClassCastException
(not needed with good variables types)
=> UIComponentTestCase - types clean-up

impl/src/test/java/jakarta/faces/component/UIComponentBaseTestCase.java
This is my mistake from https://github.com/eclipse-ee4j/mojarra/pull/5131
Really sorry for that!
=> UIComponentBaseTestCase - use spaces over tabs

impl/src/test/java/jakarta/faces/component/NamingContainerTestCase.java
Requested (needed :-)) after merging: https://github.com/eclipse-ee4j/mojarra/pull/5146.
=> NamingContainerTestCase - fix compilation error

impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java
https://github.com/eclipse-ee4j/mojarra/issues/5150
=> Mojarra issue 5150

action/pom.xml, cdi/pom.xml, impl/pom.xml, pom.xml, rest/pom.xml
=> Set version for Mojarra .Next (4.1 for now)

impl/src/main/java/jakarta/faces/component/UIComponent.java, impl/src/main/java/jakarta/faces/component/UIComponentBase.java
Fixes https://github.com/jakartaee/faces/issues/1725
=> Remove deprecated bindings field

impl/src/main/java/com/sun/faces/application/resource/ClasspathResourceHelper.java, impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java, impl/src/main/java/com/sun/faces/application/resource/WebappResourceHelper.java
=> Fixes localized composite behaviour (3.0)

impl/src/main/java/com/sun/faces/facelets/tag/faces/core/MetadataHandler.java, impl/src/main/resources/com/sun/faces/LogStrings.properties, impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml
https://github.com/jakartaee/faces/issues/1705
Mojarra will for now log a WARNING when this is not the case.
=> Clarified spec wrt location of f:metadata

impl/src/main/java/com/sun/faces/facelets/tag/faces/core/MetadataHandler.java, impl/src/main/resources/com/sun/faces/LogStrings.properties
https://github.com/jakartaee/faces/issues/1705
=> Backport WARNING message into Mojarra 4.0

impl/src/main/java/com/sun/faces/el/ELUtils.java, impl/src/main/java/com/sun/faces/el/EmptyStringToNullELResolver.java
https://github.com/eclipse-ee4j/mojarra/issues/5190
=> Add EmptyStringToNullELResolver to work around a misinterpreted change in EL3 spec

impl/src/main/java/jakarta/faces/component/behavior/FacesBehavior.java, impl/src/main/java/jakarta/faces/validator/FacesValidator.java
=> #5196 correct managed() javadoc

impl/src/main/java/com/sun/faces/context/PartialViewContextImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5189
=> Don't attempt to reconfigure PartialResponseWriter when it's already committed

impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5264
=> Added one more condition to ResourceHandlerImpl#isConnectionAbort()

impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5272
=> Extract Faces spec version from manifest

impl/src/main/java/jakarta/faces/event/PostConstructCustomScopeEvent.java, impl/src/main/java/jakarta/faces/event/PreDestroyCustomScopeEvent.java
https://github.com/jakartaee/faces/issues/1707
=> deprecate custom scope events which are unused since 4.0

impl/src/main/java/jakarta/faces/application/FacesMessage.java
https://github.com/jakartaee/faces/issues/1823
=> FacesMessage: implement equals(), hashcode(), toString()

impl/src/main/java/com/sun/faces/config/WebConfiguration.java, impl/src/main/java/jakarta/faces/application/ViewHandler.java
https://github.com/jakartaee/faces/issues/1821
=> Clarify spec wrt default of FACELETS_REFRESH_PERIOD

impl/src/main/java/jakarta/faces/application/ViewHandler.java
https://github.com/jakartaee/faces/issues/1828
=> Remove mentions in javadoc wrt backwards compatibility of facelets.* context params

impl/src/main/java/jakarta/faces/annotation/FacesConfig.java, impl/src/main/java/jakarta/faces/application/ResourceHandler.java, impl/src/main/java/jakarta/faces/application/ViewHandler.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputFile.java, impl/src/main/java/jakarta/faces/component/html/HtmlInputSecret.java
https://github.com/jakartaee/faces/issues/1830
=> Remove things marked @Deprecated(forRemoval = true, since = "4.0")

impl/src/main/java/com/sun/faces/cdi/clientwindow/ClientWindowScopeContextManager.java, impl/src/main/java/com/sun/faces/config/WebConfiguration.java
https://github.com/eclipse-ee4j/mojarra/issues/5291
=> jakarta.faces.NUMBER_OF_CLIENT_WINDOWS was not considered as context param

impl/src/main/java/jakarta/faces/component/UIViewAction.java, impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml
https://github.com/jakartaee/faces/issues/1811
=> Clarified javadoc wrt 'if' attribute and fixed wrong attr name in vdldoc

impl/src/main/java/jakarta/faces/context/ExternalContextWrapper.java, impl/src/main/java/jakarta/faces/render/Renderer.java
https://github.com/jakartaee/faces/issues/1708
=> Add missing generics to API that slipped through in Faces 4.0

impl/src/main/java/com/sun/faces/config/FacesInitializer.java, impl/src/main/java/com/sun/faces/util/Util.java
https://github.com/eclipse-ee4j/mojarra/issues/5321
=> Move back weld reinit from ConfigureListener into FacesInitializer

impl/src/main/java/jakarta/faces/component/UIInput.java
=> Faces 5.0: add UIInput.ValidateEmptyFields enum

impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java, impl/src/main/java/com/sun/faces/renderkit/ResponseStateManagerImpl.java, impl/src/main/java/jakarta/faces/application/StateManager.java, impl/src/main/java/jakarta/faces/render/ResponseStateManager.java
https://github.com/eclipse-ee4j/mojarra/issues/5333
=> Faces 5.0: add StateManager.StateSavingMethod enum

impl/src/main/java/com/sun/faces/config/InitFacesContext.java
Provide an ExceptionHandler in getExceptionHandler()
Once a solution is accepted, I'll port to master
=> [MOJARRA_5341] UnsupportedOperationException in InitFacesContext

impl/src/main/java/com/sun/faces/application/ApplicationStateInfo.java, impl/src/main/java/jakarta/faces/application/StateManager.java
#5337
https://github.com/jakartaee/faces/issues/1829
=> Faces 4.1: deprecate FSS

impl/src/main/java/com/sun/faces/config/WebConfiguration.java
https://github.com/eclipse-ee4j/mojarra/issues/5331
=> Remove unused constants for com.sun.faces.* context params

impl/src/main/java/com/sun/faces/config/ConfigureListener.java
https://github.com/eclipse-ee4j/mojarra/issues/5345
=> [4.0] [5345] Do not override application-specified "com.sun.faces.enableDistributable" value.

impl/src/main/java/com/sun/faces/config/ConfigureListener.java
https://github.com/eclipse-ee4j/mojarra/issues/5345
=> [5345] Do not override application-specified "com.sun.faces.enableDistributable" value.

impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java, impl/src/main/java/com/sun/faces/facelets/tag/faces/ComponentSupport.java, impl/src/main/resources/com/sun/faces/metadata/taglib/faces.facelets.taglib.xml
Same as #5349 but without changes to UIData. 
Next step is to move UIRepeat into jakarta.faces.component package, and to extract a common UIIterable superclass from UIData and UIRepeat as per https://github.com/jakartaee/faces/issues/963
=> Add rowStatePreserved property to UIRepeat

impl/src/main/java/com/sun/faces/cdi/CdiExtension.java, impl/src/main/java/com/sun/faces/cdi/FlowProducer.java, impl/src/main/java/jakarta/faces/flow/Flow.java
https://github.com/jakartaee/faces/issues/1342
=> Support @Inject of current flow like "@Inject Flow currentFlow"

impl/src/main/java/com/sun/faces/application/resource/FaceletWebappResourceHelper.java
https://github.com/eclipse-ee4j/mojarra/issues/5362
=> Optimized finding @View beans now the value attribute is @Nonbinding

impl/src/main/java/com/sun/faces/application/view/FaceletFullStateManagementStrategy.java, impl/src/main/java/com/sun/faces/application/view/FaceletPartialStateManagementStrategy.java, impl/src/main/java/com/sun/faces/application/view/FormOmittedChecker.java, impl/src/main/java/com/sun/faces/lifecycle/RestoreViewPhase.java
https://github.com/eclipse-ee4j/mojarra/issues/5355
=> Remove jakarta.faces.visit.SKIP_ITERATION

impl/src/main/java/com/sun/faces/lifecycle/ClientWindowFactoryImpl.java, impl/src/main/java/com/sun/faces/lifecycle/ClientWindowImpl.java, impl/src/main/java/com/sun/faces/lifecycle/TokenGenerator.java
Issue: https://github.com/eclipse-ee4j/mojarra/issues/5375
Changes:
- Modify ClientWindowImpl to generate window ID w/o using session id 
- Add TokenGenerator from MyFaces
=> [MOJARRA_5375]  The jfwid contains the session ID

impl/src/main/java/com/sun/faces/util/Util.java
https://github.com/eclipse-ee4j/mojarra/issues/5383
=> Default encoding should be prechecked

impl/src/main/java/com/sun/faces/context/FacesContextImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5408
=> Micro optimization to clarify intent of viewMap.clear() in setViewRoot()

action/pom.xml, cdi/pom.xml, impl/pom.xml, pom.xml, rest/pom.xml
=> 4.0.6 -> 4.0

impl/src/main/java/com/sun/faces/renderkit/html_basic/MenuRenderer.java
https://github.com/eclipse-ee4j/mojarra/issues/5427
=> Fix #5427 UISelectMany collectionType ignored when VE resolves to non-Collection

impl/src/main/java/com/sun/faces/config/WebConfiguration.java
https://github.com/eclipse-ee4j/mojarra/issues/5434
=> Fix #5434: Inverse default config of autoCompleteOffOnViewState

impl/src/main/java/com/sun/faces/renderkit/html_basic/MenuRenderer.java
https://github.com/eclipse-ee4j/mojarra/issues/5431
=> size attribute is only supported on HtmlSelect*Listbox components

action/pom.xml, cdi/pom.xml, impl/pom.xml, pom.xml, rest/pom.xml
=> 4.0.7 has been released

impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml, impl/src/main/resources/com/sun/faces/metadata/taglib/faces.html.taglib.xml
https://github.com/jakartaee/faces/issues/1906
While at it also noticed that f:websocket channel/scope attributes are incorrectly listed as VE, so also fixed these.
=> Fix jakartaee/faces#1906: the taglib should not accept 'var' attribute as a ValueExpression

impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java, impl/src/main/java/jakarta/faces/component/UIComponentBase.java
https://github.com/eclipse-ee4j/mojarra/issues/5460
We really need to look at being able to add new integration tests to mojarra project itself rather than faces/tck project because tck doesn't allow adding new tests to an already released major/minor version.
=> Fix regression after fixing #5417

impl/src/main/java/com/sun/faces/context/PartialViewContextImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5473
Associated PR in Faces: https://github.com/jakartaee/faces/pull/1944
=> Fix #5473: Utilize ability to pass VisitHints to UIViewRoot#resetValues()

impl/src/main/java/com/sun/faces/lifecycle/Phase.java
https://github.com/eclipse-ee4j/mojarra/issues/5491
Associated PR in Faces project: https://github.com/jakartaee/faces/pull/1965
=> Implement firing new @BeforePhase and @AfterPhase PhaseEvent qualifiers

impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java, impl/src/main/java/com/sun/faces/config/configpopulator/MojarraRuntimePopulator.java
https://github.com/eclipse-ee4j/mojarra/issues/5495
Associated PR in Faces project: https://github.com/jakartaee/faces/pull/1968
=> Register EnumConverter by converter-id as well

impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml
https://github.com/eclipse-ee4j/mojarra/issues/5493
=> Add f:resetValues tag definition back into vdldoc

impl/src/main/java/com/sun/faces/renderkit/html_basic/RadioRenderer.java, test/issue5507/pom.xml, test/issue5507/src/main/webapp/WEB-INF/web.xml, test/issue5507/src/main/webapp/issue5507.xhtml, test/issue5507/src/test/java/org/eclipse/mojarra/test/issue5507/Issue5507IT.java, test/pom.xml
https://github.com/eclipse-ee4j/mojarra/issues/5507
=> Mojarra issue 5507 select one radio with group doesnt render style class nor style

impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
Ports https://github.com/eclipse-ee4j/mojarra/pull/5532
=> Don't attempt to set response buffer size on a committed response

impl/src/main/java/com/sun/faces/renderkit/html_basic/FormRenderer.java
https://github.com/jakartaee/faces/issues/1972
=> Impl jakartaee/faces#1972: log dev stage warning when prependId is used

impl/src/main/java/com/sun/faces/application/applicationimpl/Events.java
https://github.com/jakartaee/faces/issues/1501 / https://github.com/jakartaee/faces/pull/2005
=> Fire faces system events via CDI as well

impl/src/main/java/com/sun/faces/facelets/tag/composite/RetargetedAjaxBehavior.java
=> Fix #5553 (4.0)

impl/src/main/java/com/sun/faces/context/PartialViewContextImpl.java
=> Fix resetValues in ajax requests

impl/src/main/java/com/sun/faces/cdi/ApplicationProducer.java, impl/src/main/java/com/sun/faces/cdi/CdiExtension.java, impl/src/main/java/com/sun/faces/cdi/RequestProducer.java, impl/src/main/java/com/sun/faces/cdi/SessionProducer.java, impl/src/main/java/com/sun/faces/util/ReflectionUtils.java
#5561, https://github.com/jakartaee/faces/issues/1564
Also tested in Weld, it kept working fine.
No test/tck as GlassFish doesn't use OWB.
=> Make sure #{request}, #{session} and #{application} also work in OpenWebBeans

impl/src/main/java/com/sun/faces/util/HtmlUtils.java, impl/src/test/java/com/sun/faces/util/HtmlUtilsTest.java
=> Fix #5562: support 0x10000-0x10FFFF range in XML as well

impl/src/main/java/jakarta/faces/component/UIComponentBase.java
=> Improve timing of firing PreRemoveFromViewEvent wrt children

impl/src/main/java/com/sun/faces/renderkit/ClientSideStateHelper.java, impl/src/main/java/com/sun/faces/renderkit/ServerSideStateHelper.java, impl/src/main/java/com/sun/faces/renderkit/StateHelper.java
https://github.com/eclipse-ee4j/mojarra/issues/5577
=> Fix #5577: use autocomplete="one-time-code" by default on view state hidden field

impl/src/main/java/com/sun/faces/facelets/tag/TagAttributeImpl.java, impl/src/main/java/com/sun/faces/facelets/tag/faces/CompositeComponentTagHandler.java, test/issue5584/pom.xml, test/issue5584/src/main/java/org/eclipse/mojarra/test/issue5584/Issue5584Composite.java, test/issue5584/src/main/java/org/eclipse/mojarra/test/issue5584/Issue5584NestedComposite.java, test/issue5584/src/main/webapp/WEB-INF/web.xml, test/issue5584/src/main/webapp/issue5584.xhtml, test/issue5584/src/main/webapp/resources/components/composite.xhtml, test/issue5584/src/main/webapp/resources/components/nestedComposite.xhtml, test/issue5584/src/main/webapp/resources/templates/template.xhtml, test/issue5584/src/test/java/org/eclipse/mojarra/test/issue5584/Issue5584IT.java, test/pom.xml
https://github.com/eclipse-ee4j/mojarra/issues/5584
=> Mojarra issue 5584

impl/src/main/java/com/sun/faces/util/HtmlUtils.java, impl/src/test/java/com/sun/faces/util/HtmlUtilsTest.java
https://github.com/eclipse-ee4j/mojarra/issues/5585
=> Mojarra issue 5585

impl/src/main/java/com/sun/faces/context/PartialViewContextImpl.java, test/issue5576/pom.xml, test/issue5576/src/main/java/org/eclipse/mojarra/test/issue5576/Issue5576.java, test/issue5576/src/main/webapp/WEB-INF/web.xml, test/issue5576/src/main/webapp/issue5576.xhtml, test/issue5576/src/test/java/org/eclipse/mojarra/test/issue5576/Issue5576IT.java, test/pom.xml
=> Mojarra issue 5576

action/pom.xml, cdi/pom.xml, impl/pom.xml, pom.xml, rest/pom.xml, test/base/pom.xml, test/example_jar_with_metadata_complete_false/pom.xml, test/example_jar_with_metadata_complete_true/pom.xml, test/issue5460/pom.xml, test/issue5464/pom.xml, test/issue5488/pom.xml, test/issue5503/pom.xml, test/issue5507/pom.xml, test/issue5511/pom.xml, test/issue5515/pom.xml, test/issue5541/pom.xml, test/issue5543/pom.xml, test/issue5576/pom.xml, test/issue5584/pom.xml, test/issue5594/pom.xml, test/issue5596/pom.xml, test/pom.xml
https://repo1.maven.org/maven2/org/glassfish/jakarta.faces/4.1.4/
=> 4.1.4 has been released
