- impl/pom.xml
Make the Clirr plugin not fail when reporting changes as we are now in the stage of development where we can and are removing classes and/or packages from the API.
> Fixes issue #4415 - Reconfigure Clirr plugin to be against JSF API 2.3

- api/pom.xml
- impl/pom.xml
- impl/src/main/java/javax/faces/component/UISelectMany.java
- impl/src/main/java/javax/faces/webapp/UIComponentClassicTagBase.java
- test/javaee6/correctScanningEar/pom.xml
- test/osgi/simple/pom.xml
This should fix issue #4461 by updating the versions of some plugins and some Javadoc issues.
Signed-off-by: Ingo Hoffmann <ingo@hoffmann.cx>
> Fix compilation on Java 11

- api/pom.xml
- impl/pom.xml
Build currently fails with NPE in Javadoc plugin and artifact not found for `jakarta.transaction:jakarta.transaction-api:1.3.1`. Both were fixed by upgrading them by one patch version.
> Upgrade Javadoc Plugin and Transaction API

- impl/src/main/java/com/sun/faces/facelets/tag/jsf/ValidatorTagHandlerDelegateImpl.java
- test/javaee8/cdi/src/main/java/com/sun/faces/test/javaee8/cdi/AnnotatedBean.java
- test/javaee8/cdi/src/main/java/com/sun/faces/test/javaee8/cdi/CustomBean.java
- test/javaee8/cdi/src/main/java/com/sun/faces/test/javaee8/cdi/CustomValidator1.java
- test/javaee8/cdi/src/main/java/com/sun/faces/test/javaee8/cdi/CustomValidator2.java
- test/javaee8/cdi/src/main/webapp/issue4551.xhtml
- test/javaee8/cdi/src/test/java/com/sun/faces/test/javaee8/cdi/Issue4551IT.java
This is a fix for https://github.com/eclipse-ee4j/mojarra/issues/4551
> Fix issue 4551, don't compare class name and skip CDIValidator

- impl/src/main/java/com/sun/faces/lifecycle/RestoreViewPhase.java
issue: #4577 
master PR: #4578
RestoreViewPhase is ignoring default ports 443 and 80
To validate run test Bug22995287IT on port 80 by setting integration.url=http://host/test-javaee7-protectedView
> [issue-4577] Protected view JSF page can not be accessed with port 80

- impl/src/main/java/com/sun/faces/spi/AnnotationProviderFactory.java
- impl/src/main/java/com/sun/faces/spi/ConfigurationResourceProviderFactory.java
- impl/src/main/java/com/sun/faces/spi/ServiceFactoryUtils.java
WildFly and Red Hat JBoss Enterprise Application users reports issue in https://developer.jboss.org/message/960985 and https://issues.jboss.org/browse/WFLY-6918
When a AnnotationProvider implementation doesn't have a two parameters(javax.servlet.ServletContext, com.sun.faces.spi.AnnotationProvider) which is optional,
ServiceFactoryUtils will log  a confusing NoSuchMethodException when WildFly and Red Hat JBoss Enterprise Application with a TRACE logger level enabled.
This change stop logging for expected NoSuchMethodException after it's caught.
Downstream 2.3 branch PR: https://github.com/eclipse-ee4j/mojarra/pull/4590
> Don't log expected NoSuchMethodException after it's caught.

- impl/src/main/java/com/sun/faces/el/ELUtils.java
- impl/src/test/java/com/sun/faces/el/ELUtilsTest.java
This is upstream PR for https://github.com/eclipse-ee4j/mojarra/pull/4594
During previous refactoring [1] of method `ELUtils#addEL3_0_Resolvers`, a block catching `Throwable` was replaced with block catching multiple specific exceptions:
```
if (getStreamELResolverMethod != null) {
try {
ELResolver streamELResolver = (ELResolver) getStreamELResolverMethod.invoke(expressionFactory, (Object[]) null);
composite.addRootELResolver(streamELResolver);  <-- can throw NPE
// Assume that if we have getStreamELResolver, then we must have
// javax.el.staticFieldELResolver
composite.addRootELResolver((ELResolver) newInstance("javax.el.StaticFieldELResolver"));
-           } catch (Throwable t) {
+           } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException | …
```
> Avoid NPE in ELUtils.addEL3_0_Resolvers when streamELResolver is null

- impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java
- impl/src/test/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriterTest.java
Fixes #4392
Signed-off-by: Tomas Hofman <thofman@redhat.com>
The issue is that when HtmlResponseWriter is writing CDATA text inside `<script>` or `<styles>` elements, special characters escaping is disabled. However the end CDATA sequence `]]>` should IMO still be escaped, which is the change in this PR. Not escaping `]]>` breaks AJAX response handling, see related issue.
This issue also affects Wildfly/JBoss EAP users.
> Escaping CDATA end tags

- impl/src/main/java/com/sun/faces/context/flash/ELFlash.java
Issue: #4631 
Expire 'previous' flash map and empty 'next' map at the end of RenderResponse phase. 
If the 'previous' map is needed in next request cycle, it would be moved to 'next' map - otherwise it seems it can be safely removed.
> Memory leak in FlashScope - expired elements are not cleared

- impl/src/main/java/javax/faces/component/UIViewRoot.java
- impl/src/test/java/com/sun/faces/mock/MockPartialViewContext.java
- impl/src/test/java/javax/faces/component/UIViewRootTestCase.java
Issue: https://github.com/eclipse-ee4j/mojarra/issues/4553
The fix renders the resources on update all
> Issue 4553 - Resoures#encodeAll doesn't work anymore since 2.3.x

- impl/src/main/java/javax/faces/component/UIViewRoot.java
- impl/src/test/java/com/sun/faces/mock/MockPartialViewContext.java
- impl/src/test/java/javax/faces/component/UIViewRootTestCase.java
Conflicts:
impl/src/test/java/javax/faces/component/UIViewRootTestCase.java
> [issue-4553] Resoures#encodeAll doesn't work anymore since 2.3.x

- impl/src/main/java/com/sun/faces/util/ByteArrayGuardAESCTR.java
- impl/src/test/java/com/sun/faces/util/ByteArrayGuardAESCTRTest.java
Fixes #4547 related to javaserverfaces/mojarra#4386 and PR javaserverfaces/mojarra#4412
> Fixes #4547 - ELFlash ArrayIndexOutOfBoundsException on invalid Cookie value

- impl/src/main/java/javax/faces/component/UIInput.java
- impl/src/main/java/javax/faces/component/UIViewParameter.java
- test/javaee6/viewParamNullValueAjax/pom.xml
- test/javaee6/viewParamNullValueAjax/src/main/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/TestView.java
- test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/beans.xml
- test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/glassfish-web.xml
- test/javaee6/viewParamNullValueAjax/src/main/webapp/WEB-INF/web.xml
- test/javaee6/viewParamNullValueAjax/src/main/webapp/viewparam-nullvalue-ajax.xhtml
- test/javaee6/viewParamNullValueAjax/src/test/java/com/sun/faces/test/javaee6/viewParamNullValueAjax/Issue4550IT.java
- test/servlet31/faceletsEmptyAsNull/src/test/java/com/sun/faces/test/servlet31/faceletsemptyasnull/Issue2827IT.java
As I mentioned in #issue4550
javaserverfaces/mojarra@4c74d1f  changed `submittedValue` from `null` to `""` if `javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL` is configured to true
```
if (myConsiderEmptyStringNull(context)) {
// JAVASERVERFACES_SPEC_PUBLIC-1329: If the EMPTY_STRING_SUBMITTED_VALUES_AS_NULL
// config is set, ensure that logic gets a chance to be executed
// in UIInput.processValidators().
if (null == submittedValue) {
setSubmittedValue("");
}
}
```
And it essentially makes a difference in `validate` [method](https://github.com/eclipse-ee4j/mojarra/blob/2.3.14-RELEASE/impl/src/main/java/javax/faces/component/UIInput.java#L982-#L991) in UIInput.java
```
// Submitted value == null means "the component was not submitted
// at all".
Object submittedValue = …
```
> Issue4550 alternative master

- impl/src/main/java/com/sun/faces/util/Util.java
Signed-off-by: Moulali Shikalwadi <mshikalw@redhat.com>
issue: eclipse-ee4j/mojarra#4699
> JSF trying to load DTD over the network

- impl/src/main/java/jakarta/faces/component/UIInput.java
Signed-off-by: Chao Wang <chaowan@redhat.com>
Fix for https://github.com/eclipse-ee4j/mojarra/issues/4716
Last pull request https://github.com/eclipse-ee4j/mojarra/pull/4706 addressed the JAVASERVERFACES_SPEC_PUBLIC-1329 validation requirement inside UIInput.java rather than UIViewParameter.java. However, the extra validation should have only applied on UIViewParameter.
master branch PR: https://github.com/eclipse-ee4j/mojarra/pull/4717
> This fixes #4716, make the extra validation only on UIViewParameter.

- impl/src/main/java/com/sun/faces/application/applicationimpl/Version.java
It now breaks since all faces-config files have to be converted to
jakarta, which is always at atleast 3.0.
> Do away with version check for 2.3/3.0

- impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlBasicInputRenderer.java
- test/javaee8/uiinput/src/main/java/com/sun/faces/test/javaee8/uiinput/Issue4734.java
- test/javaee8/uiinput/src/main/java/com/sun/faces/test/javaee8/uiinput/Issue4734Entity.java
- test/javaee8/uiinput/src/main/java/com/sun/faces/test/javaee8/uiinput/Issue4734EntityConverter.java
- test/javaee8/uiinput/src/main/webapp/issue4734.xhtml
- test/javaee8/uiinput/src/test/java/com/sun/faces/test/javaee8/uiinput/Issue4734IT.java
https://github.com/eclipse-ee4j/mojarra/issues/4734
Fix PropertyNotFoundException when nested entity is null while basic input renderer attempts to locate the converter by value expression type even though the submitted value is null
> https://github.com/eclipse-ee4j/mojarra/issues/4734

- impl/src/main/java/com/sun/faces/config/processor/FacesConfigNamespaceContext.java
- impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java
- impl/src/test/java/com/sun/faces/config/processor/FacesConfigNamespaceContextTest.java
Introduce a constructor to use given namespace instead of default
#4826 cherry-picked on master
> #4820 Faces 3.0 Does Not Support JavaEE NameSpace in Flow.xml Files (forward port to 4.0)

- impl/src/main/java/com/sun/faces/context/flash/ELFlash.java
Possible fix for https://github.com/eclipse-ee4j/mojarra/issues/4431
> [#4431] NPE in ELFlash.get() on first request

- impl/src/main/java/com/sun/faces/config/ConfigureListener.java
Fix for issue #4812 
As commented the same idea applied before for #3801 is used. The message is only displayed if the `WebConfiguration` instance is not null (if it is null then it was removed before by the first listener).
@arjantijms The PR is only sent to the 2.3 branch, if you need it to other branches (3.0 for example) please just let me know.
> [Issue 4812] New WARNING error message on undeploy when there are duplicate registrations of ConfigureListener

- impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java
In the `finally` of visitTree the `var` must be removed from the context
> Fix #4830: UIRepeat must clear var when finished

- impl/src/main/java/com/sun/faces/facelets/tag/jsf/ComponentSupport.java
- impl/src/main/java/javax/faces/component/ComponentStateHelper.java
- impl/src/main/java/javax/faces/component/UIComponent.java
- impl/src/main/java/javax/faces/component/UIComponentBase.java
Hi,
this is Marc from IBM. Not sure where the right place to say "Hello" is, so I will try here. Since I haven't contributed to Mojarra yet, let me quickly introduce myself. I am a Java Performance Analyst and work in the IBM Lab in Boeblingen, Germany. Nowadays, I spend most of my time improving the performance of IBM products, but I also have a long history of analyzing and optimizing the performance of customer Java applications.
One of our IBM Mainframe customers is running their COVID-19 tracing application based on Eclipse Mojarra and they asked me to analyze its performance, since they are struggling with the high amount of CPU that their application consumes. I found a number of tuning opportunities in the Mojarra code, and this patch here is one of them. Since the customer hasn't …
> Performance-optimized version of ComponentSupport.findChildByTagId()

- impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java
This is the second of my patches for the customer situation mentioned in pull request #4808. The idea of this patch here is rather simple: I noticed that in the customer's traces, there are a number of expensive, **twofold** `ResourceImpl.getURL()` calls on the _exact_ same `ResourceImpl` instance. Those expensive calls are caused by `ResourceImpl` calling `ClasspathResourceHelper.getURL()`, which in turn has to scan .jar files, etc.
My assumption is that the URL of a `ResourceImpl` instance doesn't change during the lifetime of a request. Note that I'm not proposing to statically cache a `ResourceImpl`'s URL. I only try to avoid performing a _second_ expensive call to `ClasspathResourceHelper.getURL()` inside of a `ResourceImpl` instance's `getURL()` method.
Even with my patch enabled, …
> Performance-optimized version of ResourceImpl.getURL()

- impl/src/main/java/com/sun/faces/context/AjaxExceptionHandlerImpl.java
```
Formatting the stacktrace of throwables into the log message prevents
analysis tools that integrate using log handlers from analyzing the
exception properly. Log using the Throwable parameter instead, which
should look almost the same in classical text logs, but enables
analytics using log handler integrations to work properly.
Fixes #4839
```
---
In #4839 I was instructed to open a PR for this and add tests. However, I don't quite know how I would go about testing logging output.
I am happy to add a test if you can point me to a similar test already in the repo. Otherwise I believe the change is small and obvious enough to be mergeable as-is.
> Log throwables using throwable parameter in AjaxExceptionHandlerImpl

- test2/faces23/websocket/pom.xml
- test2/faces23/websocket/src/main/webapp/WEB-INF/web.xml
- test2/faces23/websocket/src/main/webapp/spec1396DefaultWebsocket.xhtml
- test2/faces23/websocket/src/main/webapp/spec1396UserScopedWebsocket.xhtml
- test2/faces23/websocket/src/main/webapp/spec1396ViewScopedWebsocket.xhtml
- test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Issue4332IT.java
- test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Spec1396IT.java
Currently used HtmlUnit version appears to be unable to wait until a websocket is opened and also to dislike having more than one websocket open in same session. So tests had to be split. While at it, tests have also been polished.
> Fix failing f:websocket tests because of HtmlUnit internal issues

- impl/src/main/java/javax/faces/component/ComponentStateHelper.java
- impl/src/main/java/javax/faces/component/UIComponentBase.java
Compare with MyFaces BehaviorBase#restoreAttachedState as reference.
https://github.com/apache/myfaces/blob/master/api/src/main/java/jakarta/faces/component/behavior/BehaviorBase.java#L198
PrimeFaces-issues related to this PR:
primefaces/primefaces#7026
primefaces/primefaces#7181
primefaces/primefaces#6427
After this is merged we should do the same for master. (=4.0)
> #4881 Empty lists are discarded during state-saving

- impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java
- test/servlet30/resource/src/test/java/com/sun/faces/test/servlet30/resource/Issue2932IT.java
- test/servlet31/resourcehandler/src/main/java/com/sun/faces/test/servlet31/resourcehandler/ResourceHandlerTestServlet.java
Signed-off-by: Christoph Straßer <christoph.strasser78@gmail.com>
> #4800: Resources: set cache-control-header instead of expires-header (JSF 2.3)

- impl/src/main/java/com/sun/faces/application/resource/ResourceImpl.java
Signed-off-by: Christoph Straßer <christoph.strasser78@gmail.com>
> #4800: Resources: set cache-control-header instead of expires-header (JSF 4.0)

- impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriter.java
> #4925 - Guard for empty strings in html response writer

- impl/src/main/java/com/sun/faces/facelets/tag/jsf/ComponentSupport.java
- impl/src/main/java/javax/faces/component/ComponentStateHelper.java
- impl/src/main/java/javax/faces/component/UIComponent.java
- impl/src/main/java/javax/faces/component/UIComponentBase.java
https://github.com/eclipse-ee4j/mojarra/issues/4924
> Add back Performance-optimized version of ComponentSupport.findChildByTagId()

- impl/src/main/java/com/sun/faces/cdi/CdiProducer.java
- impl/src/main/java/com/sun/faces/push/WebsocketSessionManager.java
I was testing WFLY with latest CDI API (4.0.0.Alpha1) where there was a number of removals of long deprecated methods.
See eclipse-ee4j/cdi#472
This causes mojarra to crash during TCK runs so I had to create a custom artifact and replace it within WFLY - this PR a sum of changes I needed to make it work.
Since you are bound to eventually bounce into the very same issue, I thought I might as well contribute. But whether you accept it or not is OFC completely up to you :-)
Oh and I should note - the current state of this PR will work with CDI 2/3 as well as CDI 4 so there should be no harm in having it applied right away.
> CDI - make sure current state works with CDI 4.

- impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
- impl/src/main/java/jakarta/faces/context/ExternalContext.java
https://github.com/eclipse-ee4j/faces-api/issues/1570
Couldn't add a test (yet?) because glassfish didn't run localhost.
> Faces 4.0: add support for custom attributes in ExternalContext#addResponseCookie()

- impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/test/java/com/sun/faces/util/TestUtil_local.java
URI query parameters are allowed to contain non-escaped equals signs. The existing method that splits the values between the ampersands of the query fragment defaults to a limit of 0, which will result in a string array of unlimited length:
From [NavigationHandlerImpl.java](https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java):
`String[] elements = Util.split(appMap, queryElements[i], "=");`
and from [Util.java](https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/util/Util.java):
```
public synchronized static String[] split(Map<String, Object> appMap, String toSplit, String regex) {
Map<String, Pattern> patternCache = getPatternCache(appMap);
Pattern pattern = patternCache.get(regex); …
```
> JSF 2.3: Query param values containing equals sign not correctly parsed in NavigationHandlerImpl findImplicitMatch

- impl/src/main/java/com/sun/faces/renderkit/html_basic/MenuRenderer.java
Not sure this is the best way to solve this issue, but at least it works.
MyFaces (i did not debug this aspect in detail) seems to avoid this issue at all.
> Fix #4979: MenuRenderer#createCollection fails when collection is an instance of java.util.Arrays$ArrayList

- impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/test/java/com/sun/faces/util/TestUtil_local.java
[PR 4983](https://github.com/eclipse-ee4j/mojarra/pull/4983/) already merged into 2.3. This fix is for the 3.0 branch.
URI query parameters are allowed to contain non-escaped equals signs. The existing method that splits the values between the ampersands of the query fragment defaults to a limit of 0, which will result in a string array of unlimited length:
From [NavigationHandlerImpl.java](https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java):
`String[] elements = Util.split(appMap, queryElements[i], "=");`
and from [Util.java](https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/util/Util.java):
```
public synchronized static String[] split(Map<String, Object> appMap, String toSplit, …
```
> JSF 3.0 Query param values containing equals sign not correctly parsed in NavigationHandlerImpl findImplicitMatch

- impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/test/java/com/sun/faces/util/TestUtil_local.java
[PR 4983](https://github.com/eclipse-ee4j/mojarra/pull/4983/) already merged into 2.3. This fix is for the master branch.
URI query parameters are allowed to contain non-escaped equals signs. The existing method that splits the values between the ampersands of the query fragment defaults to a limit of 0, which will result in a string array of unlimited length:
From [NavigationHandlerImpl.java](https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java):
`String[] elements = Util.split(appMap, queryElements[i], "=");`
and from [Util.java](https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/util/Util.java):
```
public synchronized static String[] split(Map<String, Object> appMap, String …
```
> JSF 4.0 Query param values containing equals sign not correctly parsed in NavigationHandlerImpl findImplicitMatch

- impl/src/main/java/jakarta/faces/component/UIComponentBase.java
Fixed copypaste mistake in javadoc; it was copypasted from
unsubscribeFromEvent() method but not fully readjusted
https://github.com/eclipse-ee4j/faces-api/issues/1558
> Fixed copypaste mistake in UIComponentBase#subscribeToEvent() javadoc

- impl/src/main/java/com/sun/faces/application/ConverterPropertyEditorBase.java
- impl/src/main/java/com/sun/faces/application/NavigationHandlerImpl.java
- impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java
- impl/src/main/java/com/sun/faces/application/applicationimpl/Version.java
- impl/src/main/java/com/sun/faces/application/resource/ClientResourceInfo.java
- impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java
- impl/src/main/java/com/sun/faces/cdi/CdiExtension.java
- impl/src/main/java/com/sun/faces/cdi/CdiProducer.java
- impl/src/main/java/com/sun/faces/config/ConfigureListener.java
- impl/src/main/java/com/sun/faces/config/FacesInitializer.java
- impl/src/main/java/com/sun/faces/config/processor/ConfigProcessor.java
- impl/src/main/java/com/sun/faces/context/flash/FlashELResolver.java
- impl/src/main/java/com/sun/faces/el/ELUtils.java
- impl/src/main/java/com/sun/faces/facelets/compiler/CompilationManager.java
- impl/src/main/java/com/sun/faces/facelets/tag/DefaultTagDecorator.java
- impl/src/main/java/com/sun/faces/facelets/tag/faces/ComponentSupport.java
- impl/src/main/java/com/sun/faces/facelets/tag/faces/ComponentTagHandlerDelegateImpl.java
- impl/src/main/java/com/sun/faces/facelets/tag/ui/SchemaCompliantRemoveHandler.java
- impl/src/main/java/com/sun/faces/lifecycle/LifecycleFactoryImpl.java
- impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java
- impl/src/main/java/com/sun/faces/util/RequestStateManager.java
- impl/src/main/java/jakarta/faces/application/ViewHandler.java
- impl/src/main/java/jakarta/faces/view/ViewDeclarationLanguage.java
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.facelets.taglib.xml
- impl/src/main/resources/com/sun/faces/web-facesconfig_3_0.xsd
- Rename single occurrence of "Jakarta Server Faces" to "Jakarta Faces" in javadoc
- Rename single occurrence of "JavaServer Faces" to "Jakarta Server Faces" in 3.0 XSD
- Remove references to "jsfc" in Facelets taglib doc (those are actually unspecified in Faces spec itself, it's better to consider them a Mojarra-specific feature for now, shall probably need to be reevaluated for inclusion in a future spec)
- Rename "JSF" to "Faces" in Mojarra impl itself
> Continue renaming remaining occurrences of old names

- impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/MessagesRenderer.java
Old one was hardcoded in 2 places and one of them still had javax.
> Fix container ID of development stage messages

- impl/src/main/java/com/sun/faces/cdi/CdiExtension.java
- test2/faces22/cdiBeanValidator/pom.xml
- test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Spec1423IT.java
- test2/faces23/ajax/src/test/java/com/sun/faces/test/javaee8/ajax/Spec790IT.java
- test2/faces23/namespacedView/src/test/java/com/sun/faces/test/javaee8/namespacedView/Spec790WithNamespacedViewIT.java
- test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Issue4332IT.java
- test2/faces23/websocket/src/test/java/com/sun/faces/test/javaee8/websocket/Spec1396IT.java
- test2/faces40/inputFile/src/test/java/com/sun/faces/test/servlet50/inputfile/Spec1555IT.java
- test2/faces40/namespaces/src/main/webapp/spec1553IT.xhtml
- test2/faces40/namespaces/src/test/java/com/sun/faces/test/servlet50/namespaces/Spec1553IT.java
- ServletContainerInitializer#onStartup(classes) is always null in latest Servlet API / GlassFish --> associated tests are temporarily @Ignored (NOTE: worked fine on Tomcat 10)
- HttpServletRequest#getParameter() is always null when multipart/form-data in latest Servlet API / GlassFish --> associated tests are temporarily @Ignored (NOTE: worked fine on Tomcat 10)
- Deprecated f:verbatim was physically removed, replaced by f:subview in one test
- Temporarily permanently enable all beans for EL in CdiExtension until https://github.com/eclipse-ee4j/faces-api/issues/1594 is done
- Removed one existing @Ignore after HtmlUnit was upgraded
- Reassesed another existing @Ignore after HtmlUnit was upgraded, but appears to still fail, now with another, yet unknown cause, updated comment on this
> Fix failing tests and reactivate ignored tests

- impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
- test2/faces23/namespacedView/src/test/java/com/sun/faces/test/javaee8/namespacedView/Spec790WithNamespacedViewIT.java
It ultimately boiled down to that the `<html>` element didn't have an ID and also couldn't have one on a servlet
based environment (on a portlet based one it could have) but the test itself runs on a servlet based environment, so a kind of work around was introduced to `faces.js` to infer `render="@all"` in case the to-be-updated element was a `UIViewRoot` as well as a `NamingContainer` and the ID did not exist (previous impl threw error "During update: j_id1 not found").
FYI: entire /test2 was executed on this PR and all tests passed.
> Analyzed and fixed failing testSpec790WithNamespacedViewAjaxNavigation

- impl/src/main/java/com/sun/faces/application/view/ViewScopeManager.java
- impl/src/main/java/com/sun/faces/config/WebConfiguration.java
https://github.com/eclipse-ee4j/mojarra/issues/5038
> Add com.sun.faces.numberOfActiveViewMaps

- impl/src/main/java/com/sun/faces/renderkit/ClientSideStateHelper.java
as well as explicitly disabling com.sun.faces.clientStateTimeout when
resolved value is negative
> #4743: Fix deploy fail when com.sun.faces.clientStateTimeout is invalid

- impl/src/main/java/com/sun/faces/application/resource/ResourceCache.java
- impl/src/main/java/com/sun/faces/config/ConfigureListener.java
- impl/src/main/java/com/sun/faces/config/WebConfiguration.java
- impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
For JSF 2.3 the Servlet API version should always be at least 3.0 or newer, so all these checks are redundant.
see https://github.com/eclipse-ee4j/mojarra/issues/5061#issuecomment-1061277845
> Remove checks for Servlet < 3.0

- impl/src/main/java/com/sun/faces/facelets/tag/jsf/CompositeComponentTagHandler.java
#5065 
All tests in /test folder passed at my machine.
Associated IT is commited in Faces/tck: https://github.com/jakartaee/faces/pull/1645
> #5065: fix InsertChildrenHandler#processEvent() misbehavior caused by composite panel returning null on getId()

- impl/src/main/java/javax/faces/component/UIInput.java
- impl/src/main/java/javax/faces/component/UISelectMany.java
https://github.com/eclipse-ee4j/mojarra/issues/5081
> Fix #5081: UISelectMany#getSubmittedValue() should not default to empty string

- impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java
This is a horribly flaky issue and usually only happens when using in Firefox.
Reproducing this consistently is next to impossible.
The issue has been listed multiple times for Mojarra already, namely [#547](https://github.com/eclipse-ee4j/mojarra/issues/547) and [#4280](https://github.com/eclipse-ee4j/mojarra/issues/4280)
This occurs due to Firefox's behaviour, when sending requests for resources, but canceling/dropping the connection midway through, because the cache was faster. There are 4 possible behaviours as described on the [Mozilla support-page](https://support.mozilla.org/en-US/questions/1267945). Of the 4 cases, the ClientAbortException only happens in case 4.
The ClientAbortConnection is logged as IOException in the method call to `send404(context, resourceName, libraryName, …
> Do not log ClientAbortException

- impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java
https://github.com/eclipse-ee4j/mojarra/issues/5120
> Fix #5120: no need to doublecheck if view exists when invoked via ViewHandler#deriveLogicalViewId() instead of deriveViewId()

- impl/src/test/java/jakarta/faces/component/ValueHolderTestCaseBase.java
> Stop using Boolean constructors

- impl/src/main/java/com/sun/faces/application/view/ViewScopeContextObject.java
- impl/src/main/java/com/sun/faces/facelets/impl/DefaultFacelet.java
- impl/src/main/java/com/sun/faces/facelets/tag/AbstractTagLibrary.java
- impl/src/main/java/jakarta/faces/FacesWrapper.java
- impl/src/main/java/jakarta/faces/FactoryFinder.java
- impl/src/main/java/jakarta/faces/application/Application.java
- impl/src/main/java/jakarta/faces/application/ApplicationFactory.java
- impl/src/main/java/jakarta/faces/component/ComponentStateHelper.java
- impl/src/main/java/jakarta/faces/component/UIViewRoot.java
- impl/src/test/java/com/sun/faces/config/DigesterFactory.java
- impl/src/test/java/com/sun/faces/mock/MockApplication.java
- impl/src/test/java/com/sun/faces/xml/ParseXMLTestCase.java
- impl/src/test/java/jakarta/faces/FactoryFinderTestCase.java
- impl/src/test/java/jakarta/faces/FactoryFinderTestCase2.java
- impl/src/test/java/jakarta/faces/component/UIComponentBaseBehaviorTestCase.java
- impl/src/test/java/jakarta/faces/component/UIViewRootTestCase.java
- impl/src/test/java/jakarta/faces/webapp/ConfigFileTestCase.java
* Removed empty @return
* Fixed broken links
* Removed broken and badly placed Javadoc
* Corrected @throws declarations
* @param before @throws
> Various Javadoc fixes

- impl/src/test/java/com/sun/faces/mock/MockServletContext.java
* Add @Override
* Remove unused functions/methods
* Add raw types where they can be used
> MockServletContext - clean-up

- impl/src/test/java/com/sun/faces/mock/MockApplication.java
- impl/src/test/java/com/sun/faces/mock/MockApplicationMap.java
- impl/src/test/java/com/sun/faces/mock/MockFacesContextFactory.java
- impl/src/test/java/com/sun/faces/mock/MockHttpServletRequest.java
- impl/src/test/java/com/sun/faces/mock/MockRenderKit.java
- impl/src/test/java/com/sun/faces/mock/MockResultSet.java
- impl/src/test/java/com/sun/faces/mock/MockSessionMap.java
- impl/src/test/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriterTest.java
- impl/src/test/java/jakarta/faces/component/InputValidatorTestImpl.java
- impl/src/test/java/jakarta/faces/component/SearchExpressionHandlerTest.java
- impl/src/test/java/jakarta/faces/component/StateHolderSaverTestCase.java
- impl/src/test/java/jakarta/faces/component/UIColumnTestCase.java
- impl/src/test/java/jakarta/faces/component/UICommandTestCase.java
- impl/src/test/java/jakarta/faces/component/UIComponentBaseAttachedStateTestCase.java
- impl/src/test/java/jakarta/faces/component/UIInputTestCase.java
- impl/src/test/java/jakarta/faces/component/UIOutputTestCase.java
- impl/src/test/java/jakarta/faces/component/UIPanelTestCase.java
- impl/src/test/java/jakarta/faces/component/UIParameterTest.java
- impl/src/test/java/jakarta/faces/component/UIParameterTestCase.java
- impl/src/test/java/jakarta/faces/component/UISelectBooleanTestCase.java
- impl/src/test/java/jakarta/faces/component/UISelectItemTestCase.java
- impl/src/test/java/jakarta/faces/component/UISelectItemsTestCase.java
- impl/src/test/java/jakarta/faces/component/UISelectManyTestCase.java
- impl/src/test/java/jakarta/faces/component/UISelectOneTestCase.java
- impl/src/test/java/jakarta/faces/component/UIViewRootTestCase.java
- impl/src/test/java/jakarta/faces/component/ValueHolderTestCaseBase.java
* Fixed warnings in mocks - collective change for all warnings without changes in public interfaces
* Fixed warnings in component tests - as above
* HtmlResponseWriterTest: close writer - I know those are tests, but still, warnings easy to fix. I think this way is better than try-with-resources because any exception will break tests (and this is good)
* Remove unused code
* Remove empty UIComponent test overrides -  they don't do anything. Tests are run anyway, because of the base class. This looks like generated code waiting to be filled.
> Various fixes of warnings in tests

- impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java
- impl/src/main/java/com/sun/faces/application/ConverterPropertyEditorFactory.java
- impl/src/main/java/com/sun/faces/application/annotation/RenderKitConfigHandler.java
- impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java
- impl/src/main/java/com/sun/faces/application/view/FaceletFullStateManagementStrategy.java
- impl/src/main/java/com/sun/faces/config/processor/AbstractConfigProcessor.java
- impl/src/main/java/com/sun/faces/el/ELUtils.java
- impl/src/main/java/com/sun/faces/facelets/compiler/Compiler.java
- impl/src/main/java/com/sun/faces/facelets/tag/faces/PassThroughElementComponentHandler.java
- impl/src/main/java/com/sun/faces/facelets/tag/faces/core/PhaseListenerHandler.java
- impl/src/main/java/com/sun/faces/facelets/util/ReflectionUtil.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/MenuRenderer.java
- impl/src/main/java/com/sun/faces/spi/InjectionProviderFactory.java
- impl/src/main/java/com/sun/faces/spi/SerializationProviderFactory.java
- impl/src/main/java/com/sun/faces/util/ReflectionUtils.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/main/java/jakarta/faces/FactoryFinderInstance.java
- impl/src/main/java/jakarta/faces/application/FacesMessage.java
- impl/src/main/java/jakarta/faces/component/UIComponentBase.java
- impl/src/test/java/com/sun/faces/mock/MockApplication.java
- impl/src/test/java/jakarta/faces/component/ValueHolderTestCaseBase.java
Here and there are some other small changes in style, because of my save clean-up actions in Eclipse. If you want, I'll remove those from the commit.
> Remove newInstance() deprecation warnings

- impl/pom.xml
- impl/src/main/java/jakarta/faces/validator/BeanValidator.java
- impl/src/test/java/jakarta/faces/validator/BeanValidatorTestCase.java
Fixes #5155 
Just adding the condition to skip the validation if there is no base class. With jakarta validation the value reference can be returned with the attribute but no base class. Test was added adding the hibernate-validator dependency for testing. If you see any problem or improvement just let me know.
> Fix #5155: NPE in BeanValidator when the ValueReference has no base class

- impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
- impl/src/main/java/com/sun/faces/config/WebConfiguration.java
https://github.com/eclipse-ee4j/mojarra/issues/5164
> Mojarra issue 5164

- README.md
https://github.com/eclipse-ee4j/mojarra/issues/5165
> Update README to current state of technology

- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/main/java/javax/faces/component/UIData.java
- impl/src/test/java/com/sun/faces/util/TestUtil_local.java
Fixes https://github.com/eclipse-ee4j/mojarra/issues/5153
> Fix Mojarra issue 5153 NumberFormatException updating buttons inside facet header of a data table

- impl/src/main/java/com/sun/faces/el/ELUtils.java
- impl/src/main/java/com/sun/faces/el/EmptyStringToNullELResolver.java
https://github.com/eclipse-ee4j/mojarra/issues/5190
> Mojarra issue 5190 merged into 4 0

- impl/src/main/java/com/sun/faces/el/ELUtils.java
- impl/src/main/java/com/sun/faces/el/EmptyStringToNullELResolver.java
https://github.com/eclipse-ee4j/mojarra/issues/5190
> Mojarra issue 5190 merged into 3 0

- action/src/main/java/org/eclipse/mojarra/action/DefaultActionMappingMatcher.java
- action/src/main/java/org/eclipse/mojarra/action/DefaultActionMethodExecutor.java
- impl/src/test/java/com/sun/faces/application/FacesMessageTest.java
- impl/src/test/java/com/sun/faces/config/DigesterFactory.java
- impl/src/test/java/com/sun/faces/context/ExternalContextImplTest.java
- impl/src/test/java/com/sun/faces/el/CompositeComponentAttributesELResolverTest.java
- impl/src/test/java/com/sun/faces/junit/JUnitFacesTestCaseBase.java
- impl/src/test/java/com/sun/faces/mock/MockResultSetMetaData.java
- impl/src/test/java/com/sun/faces/mock/MockServletConfig.java
- impl/src/test/java/com/sun/faces/renderkit/html_basic/BodyRendererTest.java
- impl/src/test/java/com/sun/faces/renderkit/html_basic/HeadRendererTest.java
- impl/src/test/java/jakarta/faces/FactoryFinderTestCase.java
- impl/src/test/java/jakarta/faces/event/PhaseIdTest.java
- impl/src/test/java/jakarta/faces/model/CollectionDataModelTest.java
- impl/src/test/java/jakarta/faces/model/DataModelTestCaseBase.java
- impl/src/test/java/jakarta/faces/validator/CastingValidatorTestCase.java
- impl/src/test/java/jakarta/faces/webapp/ConfigFileTestCase.java
- rest/src/main/java/org/eclipse/mojarra/rest/DefaultRestMappingMatcher.java
- rest/src/main/java/org/eclipse/mojarra/rest/DefaultRestMethodExecutor.java
Hello again,
I've got many leftover from my work in last year with fixing warnings in project. Here are 4 of them.
* Remove various warnings from jakarta/faces tests (like you can see I had no inspiration to name these changes)
* Remove various warnings from com.sun.faces tests
* Fix compilation warnings in Action project (all warnings in subproject)
* Fix compilation warnings in Rest project (all warnings in subproject)
Since I wanted to play safe most of my work focus on test classes, so there are no worries about introducing bugs in the main code :-)
Any feedback will be appreciated. I can marge, split or delete anything from this changes.
> Fix various warnings in tests

- impl/src/main/java/com/sun/faces/spi/ServiceFactoryUtils.java
- impl/src/test/java/com/sun/faces/spi/ConfigurationResourceProviderFactoryTest.java
- impl/src/test/java/com/sun/faces/spi/MockConfigurationResourceProvider.java
- impl/src/test/java/com/sun/faces/spi/MockFacesConfigResourceProvider.java
Issue https://github.com/eclipse-ee4j/mojarra/issues/5204.
According to the official documentation of Javas Service Loader it may contain comments. Everything which comes after the '#' is considered a comment. Reference: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.html.
But Mojarras own Service Loader implementation doesn't support comments. It even doesn't skip blank lines. This leads to unexpected behaviour when using Mojarras Service Loader. When files under META-INF/services are loaded from Mojarras Service Loader it may lead to exceptions, while these service files under any other META-INF/services directory may perform perfect when they're loaded by the JDK Service Loader.
Therefore I implemented a Pull-Request which fixes that, so comments …
> Completed service file parsing.

- impl/src/main/java/com/sun/faces/application/resource/ResourcePathsIterator.java
java.lang.NullPointerException: Cannot invoke "java.util.Collection.size()" because "c" is null
at java.base/java.util.ArrayDeque.addAll(ArrayDeque.java:322)
at com.sun.faces.application.resource.ResourcePathsIterator.visit(ResourcePathsIterator.java:67)
at com.sun.faces.application.resource.ResourcePathsIterator.tryTake(ResourcePathsIterator.java:79)
at com.sun.faces.application.resource.ResourcePathsIterator.hasNext(ResourcePathsIterator.java:51)
> fix NPE if getResourcePaths return null

- impl/src/main/java/com/sun/faces/cdi/ApplicationMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/CdiProducer.java
- impl/src/main/java/com/sun/faces/cdi/ComponentProducer.java
- impl/src/main/java/com/sun/faces/cdi/CompositeComponentProducer.java
- impl/src/main/java/com/sun/faces/cdi/DataModelClassesMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ExternalContextProducer.java
- impl/src/main/java/com/sun/faces/cdi/FacesContextProducer.java
- impl/src/main/java/com/sun/faces/cdi/FlashProducer.java
- impl/src/main/java/com/sun/faces/cdi/FlowMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/HeaderMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/HeaderValuesMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/InitParameterMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ManagedPropertyProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestCookieMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestParameterMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestParameterValuesMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ResourceHandlerProducer.java
- impl/src/main/java/com/sun/faces/cdi/SessionMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ViewMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ViewProducer.java
> Make sure the beanClass attribute of all synth beans points to the CDI extension declaring them

- impl/src/main/java/com/sun/faces/renderkit/html_basic/BodyRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/HeadRenderer.java
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.html.taglib.xml
- impl/src/test/java/com/sun/faces/renderkit/html_basic/BodyRendererTest.java
- impl/src/test/java/com/sun/faces/renderkit/html_basic/HeadRendererTest.java
https://github.com/jakartaee/faces/issues/1760
- Add back id attribute to VDL of h:head and h:body
- fix HeadRenderer to only output it when actually specified
- fix BodyRenderer to only output it when HTML5 doctype is used""
> Add back id attribute to VDL of h:head and h:body

- impl/src/main/java/jakarta/faces/annotation/FacesConfig.java
https://github.com/jakartaee/faces/issues/1784
> FacesConfig#version() cannot return null

- impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java
This fixes the TCK failure introduced by issue #5120 and pr #5121
> Fix for derivePhysicalViewId broken in #5120

- impl/src/main/java/jakarta/faces/application/FacesMessage.java
Fixes #5215
A public API inner class was modified. This is not allowed according to the Signature Test rules in the Faces and EE TCKs.
cc @tandraschko @manfredriem
> Fix API signature failure

- impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
the only test that's failing is 
`Issue2906IT.testCommandLinksInRepeat`
I've looked at the test but it's quite obscure
and I'm not sure if it's well written.
I tried the view in a separate playground app
and the UI works as expected...
> faces.js Faces TCK test issues fixed.

- impl/src/main/java/com/sun/faces/cdi/SessionProducer.java
Fixes https://github.com/eclipse-ee4j/mojarra/issues/5222
> [5222] JSF pages containing #{session.id} fail with NotSerializableException when sessions are distributable

- impl/src/main/java/com/sun/faces/context/FacesContextImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5183 Quick work around for now. Cleanest solution would have been a custom scope like `@FacesContextScoped`. I'll look at it next.
> FacesContext EL variable incorrectly references previous instance after sendError() to a Facelet

- impl/src/main/java/com/sun/faces/facelets/tag/ui/UIDebug.java
In the rename from `jsfFaceletsDebug` to `faceletsDebug` a bug is introduced, due that `faceletsDebug` is a function already defined. Renaming the function from `faceletsDebug` to `faceletsDebugWindow` fixes the bug.
> Avoid name collision in generated javascript

- impl/src/main/java/com/sun/faces/cdi/SessionProducer.java
Port of https://github.com/eclipse-ee4j/mojarra/pull/5223 to 4.0 branch.
> [5222] [4.0] JSF pages containing #{session.id} fail with NotSerializableException when sessions are distributable

- impl/src/main/java/com/sun/faces/application/view/ViewMetadataImpl.java
View maps entries are not restored in "finally" block of method "ViewMetadataImpl.createMetadataView" because "currentViewMapShallowCopy" is always empty
> View maps entries are not restored in "finally" block

- impl/pom.xml
We don't need to transpile to ES5 anymore 
because Faces 4.1 will be released over 1 year after IE11 EOL.
[https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-11](https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-11)
> The Internet Explorer (IE) 11 desktop application ended support for Windows 10 semi-annual channel on June 15, 2022
This will reduce the size of the compressed file and unlock the potential of `const` and `let` optimization
> maven JS compressor - transpiler level

- impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
Replacing DOM element's innerHTML does not execute the (eventually) injected javascript.
This is standard, and we don't need to do this test anymore.
I'll leave the function only as a placeholder to identify the places where it is used in the code.
In the future a new and unique DOM replacement algorithm will replace the current functions, 
and it will be possible to remove the isAutoExec() function as well
> faces.js: isAutoExec test is not needed anymore

- impl/src/main/java/com/sun/faces/config/manager/Documents.java
https://github.com/eclipse-ee4j/mojarra/issues/5188
> Skip already-processed documents in case multiple ConfigurationResourceProviders return same documents

- impl/src/main/java/com/sun/faces/context/UrlBuilder.java
In this way we don't have to convert from String to Charset inside a for loop
and we can use the "new" `URLEncoder.encode(String,Charset)`
> UrlBuilder: Charset instead of String

- impl/src/main/java/com/sun/faces/el/ELUtils.java
- impl/src/main/java/com/sun/faces/util/Cache.java
- impl/src/main/java/com/sun/faces/util/LRUCache.java
+ LRUCache implementation adapted to the Util codebase of Faces
+ ELUtils use the new LRUCache instead of a custom local implementation
The LRUCache can also be used in other part of the code that now use
a `Collection.synchronizeMap` over the `LRUMap`
> LRUCache + ELUtils

- impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
> [5262] Do not set the response buffer size if set to -1.

- impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
- impl/src/main/java/com/sun/faces/facelets/compiler/FaceletDoctype.java
- impl/src/main/java/com/sun/faces/facelets/compiler/SAXCompiler.java
https://github.com/eclipse-ee4j/mojarra/issues/5273
> Split FaceletDoctype from HtmlDoctype as it's in prod env not recreated on every request

- impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java
- impl/src/main/java/com/sun/faces/config/configpopulator/MojarraRuntimePopulator.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/main/java/jakarta/faces/convert/UUIDConverter.java
- impl/src/main/resources/jakarta/faces/Messages.properties
- impl/src/main/resources/jakarta/faces/Messages_de.properties
- impl/src/main/resources/jakarta/faces/Messages_en.properties
- impl/src/main/resources/jakarta/faces/Messages_es.properties
- impl/src/main/resources/jakarta/faces/Messages_fr.properties
- impl/src/main/resources/jakarta/faces/Messages_pt_BR.properties
- impl/src/main/resources/jakarta/faces/Messages_zh_CN.properties
- impl/src/main/resources/jakarta/faces/Messages_zh_HK.properties
- impl/src/main/resources/jakarta/faces/Messages_zh_TW.properties
https://github.com/jakartaee/faces/issues/1819
> Add UUIDConverter

- impl/src/main/java/jakarta/faces/application/Application.java
https://github.com/jakartaee/faces/issues/1712
> Fix incorrect reference to non-existent 'context' argument in Application#unsubscribeFromEvent methods

- impl/src/main/java/com/sun/faces/config/ConfigureListener.java
- impl/src/main/java/com/sun/faces/config/FacesInitializer.java
- impl/src/main/java/com/sun/faces/util/Util.java
https://github.com/eclipse-ee4j/mojarra/issues/5232
> Mojarra fails to initialize when BDA is empty according to Weld

- impl/src/main/java/com/sun/faces/facelets/tag/composite/InsertChildrenHandler.java
- impl/src/main/java/com/sun/faces/facelets/tag/composite/RetargetedAjaxBehavior.java
- impl/src/main/java/com/sun/faces/facelets/tag/jsf/core/AjaxHandler.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
https://github.com/jakartaee/faces/issues/1567
> More robust impl of "retargeted ajax behavior" as previous impl failed in nested composites

- impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
https://github.com/jakartaee/faces/issues/1567
> Fixed regression error which caused spec1567IT to fail; the composite instance is needed further down in ComponentNotFoundException block

- impl/src/main/java/com/sun/faces/facelets/tag/composite/RetargetedAjaxBehavior.java
Fixed regression error which caused 3rd form of spec1567IT to fail; the 'this' instance being passed into getScript() was the wrong one
> https://github.com/jakartaee/faces/issues/1567

- impl/src/main/java/com/sun/faces/facelets/tag/faces/ComponentTagHandlerDelegateImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5214
E.g.
```
<cc:implementation>
<h:form> 
<cc:insertChildren>
```
caused the composite to recreate all children for cc:insertChildren brand new during render response of postback instead of reusing the ones already created during restore view.
> Composite component can't find reparented child when it's in turn in another NamingContainer within the composite

- impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java
- impl/src/main/java/com/sun/faces/application/resource/FaceletWebappResourceHelper.java
- impl/src/main/java/com/sun/faces/application/resource/ResourceManager.java
- impl/src/main/java/com/sun/faces/config/WebConfiguration.java
- impl/src/main/java/com/sun/faces/facelets/impl/DefaultFacelet.java
- impl/src/main/java/com/sun/faces/facelets/impl/DefaultFaceletFactory.java
- impl/src/main/java/com/sun/faces/facelets/tag/ui/CompositionHandler.java
- impl/src/main/java/com/sun/faces/facelets/tag/ui/DecorateHandler.java
- impl/src/main/java/com/sun/faces/facelets/tag/ui/IncludeHandler.java
- impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/ScriptStyleBaseRenderer.java
Refactor retrieval and validation of webapp contracts directory into a single place and fixed a couple of misassumptions about it always being an absolute path.
https://github.com/eclipse-ee4j/mojarra/issues/5329
> Fixed jakarta.faces.WEBAPP_CONTRACTS_DIRECTORY spec/impl mismatch

- impl/src/main/java/jakarta/faces/flow/FlowScoped.java
- impl/src/main/java/jakarta/faces/view/ViewScoped.java
https://github.com/jakartaee/faces/issues/1739
Both Mojarra and MyFaces should have this implemented. Now it's required via the faces spec.  
The tests should also be added back in the next TCK release for 4.1 / 5.0.  See  https://github.com/jakartaee/faces/pull/1741/files
> Faces 4.1: Spec 1739 - Require firing events for @Initialized, @BeforeDestroyed, and @Destroyed for build-in scopes

- impl/src/main/java/com/sun/faces/config/manager/Documents.java
- impl/src/main/java/com/sun/faces/config/processor/FacesFlowDefinitionConfigProcessor.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/test/java/com/sun/faces/config/processor/FacesConfigNamespaceContextTest.java
- impl/src/test/java/jakarta/faces/FacesConfigOrderingTestCase.java
> Improved impl of #5339

- impl/src/main/java/com/sun/faces/facelets/compiler/CompilationMessageHolder.java
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.composite.taglib.xml
https://github.com/eclipse-ee4j/mojarra/issues/5351
cc: @tandraschko
> Deprecate <composite:extension>

- impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java
- impl/src/main/java/com/sun/faces/facelets/tag/faces/ComponentSupport.java
- impl/src/main/java/jakarta/faces/component/UIData.java
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.facelets.taglib.xml
https://github.com/jakartaee/faces/issues/1263
cc: @tandraschko
> Add rowStatePreserved property to UIRepeat, exactly the same as UIData

- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.html.taglib.xml
https://github.com/jakartaee/faces/issues/1864
While at it also fixed the 'since' version for id attributes of head/body, it was actually added in 2.2 but only to renderkitdoc instead of vdldoc.
> Add missing rowStatePreserved attribute to dataTable vdl

- impl/src/main/java/jakarta/faces/annotation/View.java
https://github.com/jakartaee/faces/issues/1865
https://github.com/eclipse-ee4j/mojarra/issues/5367
> @jakarta.faces.annotation.View#value must be @Nonbinding 

- impl/src/main/java/com/sun/faces/config/ConfigureListener.java
Mojarra defines a number of initialization parameters. While "com.sun.faces.enableDistributable" is one of them, Mojarra automatically overrides any existing setting provided by the application.
If a web application wanted explicitly disable this for a distributable web application, it would normally add a servlet context parameter within web.xml.
e.g.
```
<web-app>
<distributable/>
<context-param>
<param-name>com.sun.faces.enableDistributable</param-name>
<param-value>false</param-value>
</context-param>
</web-app>
```
However, the ConfigureListener auto-enables the com.sun.faces.enableDistributable configuration property whenever it see that the tag in web.xml, overriding any custom setting.
I would expect Mojarra to respect the setting defined by the application, and only provide a …
> [2.3] Do not override application-specified "com.sun.faces.enableDistributable" value

- .github/workflows/build.yml
- impl/pom.xml
- impl/src/main/java/com/sun/faces/application/ConverterPropertyEditorFactory.java
- impl/src/main/java/com/sun/faces/application/applicationimpl/ExpressionLanguage.java
- impl/src/main/java/com/sun/faces/application/resource/ResourceHelper.java
- impl/src/main/java/com/sun/faces/application/view/FaceletFullStateManagementStrategy.java
- impl/src/main/java/com/sun/faces/context/flash/ELFlash.java
- impl/src/main/java/com/sun/faces/context/flash/FlashELResolver.java
- impl/src/main/java/com/sun/faces/el/ChainTypeCompositeELResolver.java
- impl/src/main/java/com/sun/faces/el/CompositeComponentAttributesELResolver.java
- impl/src/main/java/com/sun/faces/el/DemuxCompositeELResolver.java
- impl/src/main/java/com/sun/faces/el/ELUtils.java
- impl/src/main/java/com/sun/faces/el/EmptyStringToNullELResolver.java
- impl/src/main/java/com/sun/faces/el/FacesResourceBundleELResolver.java
- impl/src/main/java/com/sun/faces/el/ResourceELResolver.java
- impl/src/main/java/com/sun/faces/el/ScopedAttributeELResolver.java
- impl/src/main/java/com/sun/faces/facelets/tag/AbstractTagLibrary.java
- impl/src/main/java/com/sun/faces/util/ELAwareBeanManagerWrapper.java
- impl/src/main/java/com/sun/faces/util/MojarraThreadFactory.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/main/java/jakarta/faces/ServletContextFacesContextFactory.java
- impl/src/test/java/com/sun/faces/mock/MockBeanManager.java
- impl/src/test/java/com/sun/faces/mock/MockELResolver.java
- impl/src/test/java/com/sun/faces/mock/MockHttpServletResponse.java
- pom.xml
Update dependencies to their M1 versions where applicable, and update code to support this.
Set release target to JDK 17, and removed some resulting warnings.
> Support for the Jakarta EE 11 M1 release

- impl/src/main/java/jakarta/faces/component/UIInput.java
https://github.com/eclipse-ee4j/mojarra/issues/5386
> UIInput#getSubmittedValue() must also consider isLocalValueSet() when INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL=true

- impl/src/main/java/com/sun/faces/RIConstants.java
- impl/src/main/java/com/sun/faces/application/ConverterPropertyEditorFactory.java
- impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
- impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java
- impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
- impl/src/main/java/com/sun/faces/context/PartialViewContextImpl.java
- impl/src/main/java/com/sun/faces/context/UrlBuilder.java
- impl/src/main/java/com/sun/faces/context/flash/ELFlash.java
- impl/src/main/java/com/sun/faces/facelets/util/Classpath.java
- impl/src/main/java/com/sun/faces/lifecycle/RestoreViewPhase.java
- impl/src/main/java/com/sun/faces/renderkit/StateHelper.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/OutputLinkRenderer.java
- impl/src/main/java/com/sun/faces/util/Util.java
- impl/src/main/java/jakarta/faces/application/ViewHandler.java
- impl/src/main/java/jakarta/faces/context/PartialResponseWriter.java
#5383 
Review/cleanup/refactor all code logic related to managing facelets/request/response encoding and centralized in a new `Util#getResponseEncoding()` method.
Also took the opportunity to get rid of all hardcoded strings representing `"UTF-8"` throughout the source code and replace them by `StandardCharsets.UTF_8` (`.name()`)
> #5383 cleanup facelets encoding management

- impl/src/main/java/com/sun/faces/facelets/impl/DefaultFacelet.java
Fixed wrong base url to validate contracts resource; it should be validated against the path of the parent facelet not against the resolved url of the include
https://github.com/eclipse-ee4j/mojarra/issues/5389
> #5389: Fix wrong base url to validate contracts resource

- impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
Fix failing ajax related TCK tests caused by non-existent numeric input attribute being interpreted as -1 which was disallowed when put back as numeric input attribute which only allowed positive integers. It caused a JS error like so
> Failed to set the 'maxLength' propertry on 'HTMLInputElement': The value provided (-1) is not positive or 0.
> Fix TCK for Mojarra 4.1

- impl/src/main/java/com/sun/faces/util/Util.java
Discovered while restoring websocket tests in TCK.
> Fix ClassCastException on CDI.current().getBeanManager() call triggered during websocket push (during which there's no FacesContext)

- impl/src/main/java/com/sun/faces/config/processor/ApplicationConfigProcessor.java
There's an outer catch that will log it.
> No need to swallow exception at that point.

- impl/src/main/java/com/sun/faces/application/view/ViewScopeContextManager.java
- impl/src/main/java/com/sun/faces/cdi/clientwindow/ClientWindowScopeContextManager.java
- impl/src/main/java/com/sun/faces/config/ConfigureListener.java
- impl/src/main/java/com/sun/faces/context/SessionMap.java
- impl/src/main/java/com/sun/faces/lifecycle/ClientWindowImpl.java
- impl/src/main/java/com/sun/faces/renderkit/ServerSideStateHelper.java
https://github.com/eclipse-ee4j/mojarra/issues/5380
> Add session mutex

- impl/src/main/java/com/sun/faces/application/resource/ResourceHandlerImpl.java
https://github.com/eclipse-ee4j/mojarra/issues/5391
> Consider ClosedChannelException as well when checking for connection abort

- impl/src/main/java/com/sun/faces/config/manager/FacesSchema.java
- impl/src/main/resources/com/sun/faces/jakartaee_11.xsd
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.composite.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.core.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.facelets.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.html.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.passthrough.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/tags.core.taglib.xml
- impl/src/main/resources/com/sun/faces/metadata/taglib/tags.functions.taglib.xml
- impl/src/main/resources/com/sun/faces/web-facelettaglibrary_4_1.xsd
- impl/src/main/resources/com/sun/faces/web-facesconfig_4_1.xsd
- impl/src/main/resources/com/sun/faces/web-partialresponse_4_1.xsd
corresponding PR in Faces https://github.com/jakartaee/faces/pull/1900
> add xsds for 4.1

- impl/src/main/java/com/sun/faces/lifecycle/ApplyRequestValuesPhase.java
- impl/src/main/java/com/sun/faces/lifecycle/InvokeApplicationPhase.java
- impl/src/main/java/com/sun/faces/lifecycle/ProcessValidationsPhase.java
- impl/src/main/java/com/sun/faces/lifecycle/UpdateModelValuesPhase.java
Reduce logging level of exception which is already rethrown during processing a lifecycle phase -- this only causes duplicate logs https://github.com/eclipse-ee4j/mojarra/issues/5404
> Reduce logging level of exception which is already rethrown

- impl/src/main/java/com/sun/faces/application/applicationimpl/InstanceFactory.java
https://github.com/eclipse-ee4j/mojarra/issues/5417
~Hold on with proactively merging. I want to run TCK before merge just to ensure there are no corner cases which depend on this "optimization".~ TCK passed.
(sorry for imports being shuffled in the code diff, I reconfigured Eclipse to treat jakarta.* the same way as javax.*)
> #5417: remove "optimization" when composite attribute default is literal instead of VE, this will fail when the final value itself is VE

- impl/src/main/java/com/sun/faces/config/configpopulator/MojarraRuntimePopulator.java
- impl/src/main/java/com/sun/faces/config/processor/FactoryConfigProcessor.java
- impl/src/main/java/com/sun/faces/webapp/FacesServletFactoryImpl.java
> Fix FacesServletFactory

- impl/src/main/java/com/sun/faces/util/Util.java
This backports https://github.com/eclipse-ee4j/mojarra/pull/5401 into the 4.0 branch. 
Resolves https://github.com/eclipse-ee4j/mojarra/issues/5429
> Backport: Default encoding should be prechecked

- impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java
Fix #5414 only http/2-push real faces resource urls coming from resource components/annotations and thus not just any url which happens to be passed through encodeResourceURL
> Only http/2-push real faces resource urls

- impl/src/main/java/com/sun/faces/application/view/ViewHandlingStrategyManager.java
- impl/src/main/java/com/sun/faces/application/view/ViewHandlingStrategyNotFoundException.java
when migrating to extensionless I had an issue in production where I was getting an exception
```
2024-04-01 14:04:46,373 SEVERE [jakarta.enterprise.resource.webcontainer.faces.application] (default task-347) Error Rendering View[/s/home.xhtml]: com.sun.faces.application.view.ViewHandlingStrategyNotFoundException
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at jakarta.faces.impl@4.0.5//com.sun.faces.application.view.ViewHandlingStrategyManager.getStrategy(ViewHandlingStrategyManager.java:57)
at jakarta.faces.impl@4.0.5//com.sun.faces.application.view.ViewDeclarationLanguageFactoryImpl.getViewDeclarationLanguage(ViewDeclarationLanguageFactoryImpl.java:45)
at jakarta.faces.impl@4.0.5//com.sun.faces.application.view.MultiViewHandler.getViewDeclarationLanguage(MultiViewHandle …
```
> show which viewId was not found in exception

- impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
- impl/src/main/java/jakarta/faces/component/UIData.java
Fix #5445: problem was two-fold:
- UIData#invokeOnComponent shouldn't have skipped non-UIColumn kids
- A FacesException while trying to locate dynamic component should not have blocked the view build time
> Fix #5445 Dynamic actions not correctly processed

- impl/src/main/java/jakarta/faces/component/UIComponentBase.java
https://github.com/eclipse-ee4j/mojarra/issues/5445
Essentially, while removing children, they (naturally) don't expect the parent to already be removed at that point.
Wait with merging. I want to run entire TCK on this just to exclude this was done intentionally by the original developer.
> Improve timing of firing PreRemoveFromViewEvent wrt children

- impl/src/main/java/com/sun/faces/cdi/ApplicationMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/CdiExtension.java
- impl/src/main/java/com/sun/faces/cdi/CdiProducer.java
- impl/src/main/java/com/sun/faces/cdi/CdiUtils.java
- impl/src/main/java/com/sun/faces/cdi/ComponentProducer.java
- impl/src/main/java/com/sun/faces/cdi/CompositeComponentProducer.java
- impl/src/main/java/com/sun/faces/cdi/DataModelClassesMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ExternalContextProducer.java
- impl/src/main/java/com/sun/faces/cdi/FacesContextProducer.java
- impl/src/main/java/com/sun/faces/cdi/FlashProducer.java
- impl/src/main/java/com/sun/faces/cdi/FlowMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/HeaderMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/HeaderValuesMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/InitParameterMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ManagedPropertyProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestCookieMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestParameterMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/RequestParameterValuesMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ResourceHandlerProducer.java
- impl/src/main/java/com/sun/faces/cdi/SessionMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ViewMapProducer.java
- impl/src/main/java/com/sun/faces/cdi/ViewProducer.java
- impl/src/main/java/com/sun/faces/context/FacesContextImpl.java
Fix #5457: revert removal of getBeanClass on Faces artifact producers; adjust it to check if Weld is used and if so return CdiExtension.class
> Fix 5457: revert removal of getBeanClass on Faces artifact producers

- impl/src/main/java/com/sun/faces/util/HtmlUtils.java
- impl/src/test/java/com/sun/faces/util/HtmlUtilsTest.java
https://github.com/eclipse-ee4j/mojarra/issues/5464
> Fix XML escaping when writing attributes

- impl/src/main/java/com/sun/faces/application/ApplicationAssociate.java
- impl/src/main/java/com/sun/faces/application/ApplicationImpl.java
- impl/src/main/java/com/sun/faces/application/ResolversRegistry.java
- impl/src/main/java/com/sun/faces/el/ELUtils.java
Fixes #5461
This avoids sharing resolvers between multiple applications on the classpath and also avoids memory leaks in application servers after an application and its classloaders are undeployed.
Resolvers are tied to the Faces Application instance.
> Move global EL resolvers from static variables to application variables

- impl/src/main/java/com/sun/faces/application/ResolversRegistry.java
- impl/src/main/java/com/sun/faces/el/ELUtils.java
> Add expression language 6.0 Optional and Record resolvers

- impl/src/main/java/jakarta/faces/context/FacesContext.java
https://github.com/eclipse-ee4j/mojarra/issues/5484
> Fix #5484: api classes should not have impl dependencies

- impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
Fixes #5499.
The null reference has been occurring since `if (node && node.parentNode) node.parentNode.removeChild(node);` is replaced with `if (node) node.remove();` in the commit f2f343a.
It can be fixed by adding a null check for `node.parentNode` as before.
> Fix null reference error when calling faces.ajax.request()

- impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
This backports #5500 into the 4.1 branch.
Fixes #5499.
> Backport: Fix null reference error when calling faces.ajax.request()

- impl/src/main/java/com/sun/faces/renderkit/html_basic/ButtonRenderer.java
Fix #5488: non-action ajax event shouldn't trigger action event; while at it also cleaned up existing code comments
IT is via commit https://github.com/eclipse-ee4j/mojarra/pull/5469/commits/25b9aedb566c3a81c0f47adbecd66fe0df790b66 added to the still pending PR https://github.com/eclipse-ee4j/mojarra/pull/5469 (with the long term purpose to move it into the TCK when next Faces version is to be released because the TCK setup in its current form doesn't allow adding new ITs for an already released version)
> Fix #5488: non-action ajax event shouldn't trigger action event

- impl/src/main/java/com/sun/faces/util/HtmlUtils.java
- pom.xml
- test/base/pom.xml
- test/base/src/main/java/org/eclipse/mojarra/test/base/BaseIT.java
- test/issue5460/pom.xml
- test/issue5460/src/main/java/org/eclipse/mojarra/test/issue5460/Issue5460Bean.java
- test/issue5460/src/main/java/org/eclipse/mojarra/test/issue5460/Issue5460Component.java
- test/issue5460/src/main/webapp/WEB-INF/web.xml
- test/issue5460/src/main/webapp/issue5460.xhtml
- test/issue5460/src/main/webapp/resources/components/component.xhtml
- test/issue5460/src/test/java/org/eclipse/mojarra/test/issue5460/Issue5460IT.java
- test/issue5464/pom.xml
- test/issue5464/src/main/java/org/eclipse/mojarra/test/issue5464/Issue5464Bean.java
- test/issue5464/src/main/webapp/WEB-INF/web.xml
- test/issue5464/src/main/webapp/issue5464.xhtml
- test/issue5464/src/test/java/org/eclipse/mojarra/test/issue5464/Issue5464IT.java
- test/issue5488/pom.xml
- test/issue5488/src/main/java/org/eclipse/mojarra/test/issue5488/Issue5488Bean.java
- test/issue5488/src/main/webapp/WEB-INF/web.xml
- test/issue5488/src/main/webapp/issue5488.xhtml
- test/issue5488/src/test/java/org/eclipse/mojarra/test/issue5488/Issue5488IT.java
- test/pom.xml
Also added IT tests for #5460 and #5464 and spotted one more place where #5464 should be fixed.
NOTE: the technical reason for adding back the IT config to Mojarra project is because we CANNOT add new tests to the TCK of an already-released Faces version. We can only add them for the next Faces version. But this also means that these won't be executed when the current version is being patched/bugfixed. Hence we can only add them to the Mojarra project. Once a next TCK version is to be prepared we can simply move them from Mojarra into Faces project for TCK.
> Add minimal configuration for integration tests

- impl/src/main/java/com/sun/faces/renderkit/html_basic/MessageRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/MessagesRenderer.java
- impl/src/main/resources/com/sun/faces/metadata/taglib/faces.html.taglib.xml
- impl/src/main/resources/com/sun/faces/standard-html-renderkit.xml
https://github.com/eclipse-ee4j/mojarra/issues/5489
Associated PR in Faces side: https://github.com/jakartaee/faces/pull/1964
> Support new FacesMessage.Severity.SUCCESS in h:message/h:messages

- impl/src/main/java/jakarta/faces/component/UIViewRoot.java
https://github.com/eclipse-ee4j/mojarra/issues/5513
> Backport #5513 from 5.0 into 4.0

- impl/src/main/java/com/sun/faces/config/manager/tasks/ProvideMetadataToAnnotationScanTask.java
- test/example_jar_with_metadata_complete_false/pom.xml
- test/example_jar_with_metadata_complete_false/src/main/java/org/eclipse/mojarra/test/example_jar_with_metadata_complete_false/ExampleFacesComponent.java
- test/example_jar_with_metadata_complete_false/src/main/resources/META-INF/faces-config.xml
- test/example_jar_with_metadata_complete_true/pom.xml
- test/example_jar_with_metadata_complete_true/src/main/java/org/eclipse/mojarra/test/example_jar_with_metadata_complete_true/ExampleFacesComponent.java
- test/example_jar_with_metadata_complete_true/src/main/resources/META-INF/faces-config.xml
- test/issue5507/src/main/webapp/WEB-INF/web.xml
- test/issue5511/pom.xml
- test/issue5511/src/main/webapp/WEB-INF/web.xml
- test/issue5511/src/main/webapp/issue5511-using-jar-with-metadata-complete-false.xhtml
- test/issue5511/src/main/webapp/issue5511-using-jar-with-metadata-complete-true.xhtml
- test/issue5511/src/test/java/org/eclipse/mojarra/test/issue5511/Issue5511IT.java
- test/pom.xml
Fix #5511: don't anymore rely on CodeSource#getLocation(), instead obtain the URL of the resource itself via its own class loader
> Fix #5511: don't anymore rely on CodeSource#getLocation()

- impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
Changes made to fix https://github.com/eclipse-ee4j/mojarra/issues/5164 and https://github.com/eclipse-ee4j/mojarra/issues/5262 causes breakages in the Jakarta EE 10 Security TCK (specifically in the "old" bit).
```
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/securityapi/ham/customform/base/Client.java#testCustomFormHAMHasCorrectQualifier
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/securityapi/ham/customform/base/Client.java#testCustomFormHAMValidateRequest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/securityapi/ham/customform/base/Client.java#testCustomFormLoginToContinueErrorPage
```
This is reproducible in Payara 6 and GlassFish 7 when using a Mojarra version higher than 4.0.0 (the first change was introduced in …
> Don't attempt to set response buffer size on a committed response

- impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java
Fixes https://github.com/eclipse-ee4j/mojarra/issues/5525.
I assume mapping is not null, but the assumption was in the previous version as well by means of calling .startsWith(mapping).
Project builds, and the fix can be tested by trivial example where facesServlet would be mapped to /*.
> Handle empty mapping in normalizeRequestURI

- impl/src/main/java/com/sun/faces/config/ConfigureListener.java
- impl/src/main/java/com/sun/faces/config/FacesInitializer.java
- impl/src/main/java/com/sun/faces/lifecycle/Phase.java
- impl/src/main/java/com/sun/faces/util/Util.java
Fixed two issues discovered while finally getting Faces 5.0 / Mojarra 5.0 TCK to work as per https://github.com/jakartaee/faces/pull/1988
- new `FacesConfig.ContextParam` cannot be checked in `FacesInitializer` because there is no guarantee that CDI is present at that moment (due to `ServletContainerInitializer` ordering being undefined, see also https://github.com/jakartaee/servlet/issues/548), so logic has been moved into `ConfigureListener`
- fix regression of https://github.com/eclipse-ee4j/mojarra/issues/5491 it caused `java.lang.NullPointerException: Cannot invoke
"jakarta.faces.event.PhaseEvent.getPhaseId()" because "event" is null` when an empty project is deployed which has no phase listeners
> Fix mojarra 5 initialization with empty dd files

- impl/src/main/java/com/sun/faces/util/MessageFactory.java
- impl/src/main/java/jakarta/faces/validator/MessageFactory.java
Fix identity of BindingFacesMessage; it broke since introduction of equals/hashCode for FacesMessage in
https://github.com/jakartaee/faces/issues/1823
Reproducer: trigger 2 different bean validation errors on the same property, it should show 2 separate messages instead of only the last one.
Discovered while analyzing o:validateBean IT failure since switching from Mojarra 4.0.x to 4.1.x.
> Fix identity of BindingFacesMessage

- impl/src/main/java/com/sun/faces/renderkit/ResponseStateManagerImpl.java
https://github.com/jakartaee/faces/issues/1999
Corresponding PR in Faces: https://github.com/jakartaee/faces/pull/2000
> Fix jakartaee/faces#1999: default of jakarta.faces.STATE_SAVING_METHOD is actually "server"

- impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
- impl/src/main/java/com/sun/faces/util/Util.java
- test/issue5543/pom.xml
- test/issue5543/src/main/java/org/eclipse/mojarra/test/issue5543/Issue5543Bean.java
- test/issue5543/src/main/webapp/WEB-INF/web.xml
- test/issue5543/src/main/webapp/issue5543.xhtml
- test/issue5543/src/test/java/org/eclipse/mojarra/test/issue5543/Issue5543IT.java
- test/pom.xml
> Fix Response encoding not stored in the ext context session #5543

- impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java
https://github.com/jakartaee/faces/pull/2006
> Fix corner case after implementing jakartaee/faces#1507 integration test

- impl/src/main/java/com/sun/faces/config/InitFacesContext.java
- impl/src/main/java/com/sun/faces/config/initfacescontext/ServletContextAdapter.java
- impl/src/test/java/com/sun/faces/application/WebappLifecycleListenerTestCase.java
Proposal to fix https://github.com/eclipse-ee4j/mojarra/issues/5556
Also contains a unit test reproducing the broken exception handling.
> [4.0] Fix exception handling in WebappLifecycleListener#requestDestroyed()

- impl/src/main/java/com/sun/faces/facelets/tag/ui/UIDebug.java
- impl/src/main/java/com/sun/faces/renderkit/RenderKitUtils.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/ButtonRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/CheckboxRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/CommandLinkRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/CommandScriptRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/MenuRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/OutcomeTargetButtonRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/RadioRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/SecretRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/SelectManyCheckboxListRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/TextRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/TextareaRenderer.java
- impl/src/main/java/com/sun/faces/renderkit/html_basic/WebsocketRenderer.java
- impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js
First step for jakartaee/faces#1590: convert all Mojarra-generated inline event handlers to attached event handlers so they are at least CSP compatible
> First step for jakartaee/faces#1590
